### ISSUE TITLE
Next!

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#1]
Features to develop for next versions:
- [x] Landsat / Sentinel bands ratio (e.g NDVI)
- [ ] Improve Landsat pan-sharpening
- [ ] Add Modis support (https://aws.amazon.com/public-datasets/modis/)
- [x] Add SRTM support (https://aws.amazon.com/public-datasets/terrain/)

**Comment by scarmuega** [comment]
@vincentsarago I was going to implement SRTM for another project, but I would gladly contribute here if it's something that you're interested in. If so, please let me know and I'll start a PR.

**Comment by vincentsarago** [comment]
👋 @scarmuega, that will be great!
Some info about Terrain data on AWS: https://aws.amazon.com/public-datasets/terrain/

GeoTIFF and PNG are already available, so I'm not sure what we should do. It may have nothing to do with rio-tiler, but more with handler function like https://github.com/mapbox/landsat-tiler so create high level tile services ? 

BTW, I think the real next step will be #5.

**Comment by scarmuega** [comment]
My idea was that rio-tiler could handle hill shading and color relief transformations from the raw elevation data in AWS, so that it outputs a ready-to-show tile, having the color-maps and z-factor as parameters.

**Comment by vincentsarago** [comment]
We could totally implement utility functions to create the hill shading and color relief. Just keep in mind that we'd like to keep module dependency as low as possible to be able to ship rio-tiler in AWS lambda-function. 

Feel free to start a PR ;-)

**Comment by vincentsarago** [comment]
I'm going to close this ticket. 
FYI, to create tile from elevation data we can use the Terrain dataset hosted on AWS. In previous commits we added some utility functions to work with elevation data (https://github.com/cogeotiff/rio-tiler/commit/d0f40a690434481d11d191733f51b77be7937745, https://github.com/cogeotiff/rio-tiler/commit/9853eb308a745ce9ebc8c66a26cbfa405882cbf9) 

example: https://github.com/RemotePixel/remotepixel-tiler/blob/master/remotepixel_tiler/main.py#L76-L82
