### ISSUE TITLE
Apply same resampling method for mask and tile

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#105]
in https://github.com/cogeotiff/rio-tiler/blob/2bf9f144958ae226af4db338487e8a34159550be/rio_tiler/utils.py#L345-L353
we could end up (actual behavior) with using different resampling for mask and data which will result in bad masking.

**Comment by vincentsarago** [comment]
@dionhaefner
Am I missing something here ? it seems to be the same in terracotta https://github.com/DHI-GRAS/terracotta/blob/master/terracotta/drivers/raster_base.py#L524-L529

**Comment by vincentsarago** [comment]
Confirmed! 
<img width="868" alt="Capture d’écran, le 2019-05-10 à 12 47 38" src="https://user-images.githubusercontent.com/10407788/57543272-ed11ea00-7321-11e9-85ec-7cbacb407b4a.png">

**Comment by vincentsarago** [comment]
closed by #106

**Comment by dionhaefner** [comment]
IIRC this was deliberate. We used to use the same resampling for the alpha mask, but it eroded the tile edges. E.g. linear resampling doesn't make much sense on a binary mask, does it?

**Comment by vincentsarago** [comment]
@dionhaefner well I'm not sure how it does on a pure binary mask but at least when dealing with mask built from nodata it will mater. 
Will need to test on pure alpha/binary mask

**Comment by dionhaefner** [comment]
When I played around with this, using resampling for the mask never had a positive effect. But YMMV

**Comment by vincentsarago** [comment]
Well it seems that this introduced a bug when dealing with internal mask (wonder why the tests didn't caught this) 

When using bilinear resampling the mask is =255 everywhere

**Comment by vincentsarago** [comment]
Well this is really strange I could not reproduce the bug (bilinear resampling of mask creating non-masked data) when using Rasterio wheels ... so I guess this has to deal with my gdal/numpy install 🤔 . 

BUT I found that using something else than nearest resampling introduce mask artefacts ... I'm going to revert the change introduced in #106 

I'm really sorry for the users that could have been impacted by the 1.2.6 release

**Comment by vincentsarago** [comment]
Note: if we revert #106
this test : https://github.com/cogeotiff/rio-tiler/blob/156b0a8a0f12125d7c5ff45d04a00e0ba6321640/tests/test_utils.py#L753-L756

fails which seems a bit strange. I'll investigate a bit more and might open an issue on rasterio

**Comment by vincentsarago** [comment]
closed by https://github.com/cogeotiff/rio-tiler/commit/d9e532a6454f71475f3056cbd2b0bfdb3bd9e497
