### ISSUE TITLE
create a conda package 

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#112]
ref https://github.com/CosmiQ/solaris/issues/163#issuecomment-509447651

how-to: https://conda-forge.readthedocs.io/en/latest/recipe.html

**Comment by nrweir** [comment]
As I'm the one requesting this functionality, I'd be more than happy to help put together a conda-forge feedstock! They tend to be pretty low-maintenance for packages with few dependencies.

**Comment by nrweir** [comment]
@vincentsarago the only challenge with putting together conda-forge feedstocks (or any conda recipe) is that all of the dependencies also need to be conda packages. The only one that I see which isn't available on conda is `rio-toa`, which I see is important for landsat processing. Looking at that project in turn I don't see any packages that aren't up on conda, so that would be the only additional task.

**Comment by vincentsarago** [comment]
😞 rio-toa is not maintained and I'm affraid it's going to take time to update.

**Comment by nrweir** [comment]
Got it. To be honest, creating a conda-forge recipe for a package that's on pypi doesn't even necessarily require any updates to the codebase itself - particularly if the project isn't being maintained there won't be a lot that needs to be done once it's up. If those folks wouldn't care I'd be happy to create a conda-forge recipe for it as well.

**Comment by nrweir** [comment]
Hey @vincentsarago, as I was re-visiting this, I noticed that there's no license in the [rio-toa](https://github.com/mapbox/rio-toa) repo. The only reference to one is in the setup.py file, which lists `license="BSD"`, though doesn't specify which. I was checking to see if the license they use permits re-distribution, in which case I could have just popped the repo onto conda-forge myself and gotten the process going. I'll probably have to hold off without the license there, so I'll likely leave this be for now.

**Comment by nrweir** [comment]
Hey @vincentsarago, as I was re-visiting this, I noticed that there's no license in the [rio-toa](https://github.com/mapbox/rio-toa) repo. The only reference to one is in the setup.py file, which lists `license="BSD"`, though doesn't specify which. I was checking to see if the license they use permits re-distribution, in which case I could have just popped the repo onto conda-forge myself and gotten the process going. I'll probably have to hold off without the license there, so I'll likely leave this be for now.

**Comment by lsetiawan** [comment]
Hey @vincentsarago and @nrweir, I've added `rio-tiler` and its dependencies to `conda-forge`. In regards to `rio-toa`. I've put in the license as BSD-3-Clause mirroring `rio-tiler`. I hope that works for now. It can be changed anytime. Thanks.

@nrweir can I add you to the conda package maintainer list?

**Comment by nrweir** [comment]
@lsetiawan sure! Thanks for this!

**Comment by kylebarron** [comment]
I'm guessing that `rio-toa` and `rio-mucho` aren't updated anymore, so it's probably ok at least for now to include them directly in the `rio-tiler` conda package instead of making separate packages for them.

**Comment by kylebarron** [comment]
This issue can probably be closed now; see https://anaconda.org/conda-forge/rio-tiler. I think that the conda recipe maintainers might get notifications when new versions are published to pypi? (at least non-alpha/beta versions)

**Comment by vincentsarago** [comment]
>  I think that the conda recipe maintainers might get notifications when new versions are published to pypi? (at least non-alpha/beta versions)

yeah basically that's what I wanted to know before closing this 

also good to know rio-toa and rio-mucho won't be needed for rio-tiler 2.0 (only for rio-tiler-pds plugin,.... which we will need to put in conda at one point)

**Comment by lsetiawan** [comment]
@kylebarron @vincentsarago Conda-forge now has a bot that detects new versions, and will make an automatic PR to the recipe, at which point the maintainer can choose to merge. :smile:
