### ISSUE TITLE
Possibly incorrect calculation of overview size

### ISSUE THREAD

**Issue by perliedman** [cogeotiff/rio-tiler#116]
Hi! Thanks for a really great library, it has been a breeze working with, and the code is very clear to read.

While working with rio-tiler I stumbled upon what I think might be an error in how the size of  overviews are calculated in `utils.raster_get_stats` (https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/utils.py#L187): since integer division is used, any fractions will always be rounded down. Looking at the output from `gdalinfo`, it seems to always round fractions _up_ to the next integer size instead. I have not been able to find out what the spec actually says, but I am tempted to trust `gdalinfo`.

If my guess is correct, this might cause the overview to be unnecessarily scaled since the size is off by one.

**Comment by vincentsarago** [comment]
@perliedman I didn't think to much about it so thanks for this issue 😄 
I'll have a look to see if we need to change it 

Thanks

**Comment by vincentsarago** [comment]
@perliedman this should be fixed now. I just deployed the new package on pypi ! 

Thanks for reporting this issue
