### ISSUE TITLE
Explore SOURCE_EXTRA (GDALWarpOptions) for tile tile_edge_padding

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#121]
@rowanwins, in #104 we introduced the `tile_edge_padding` argument but to me it seems that instead of doing so we could pass the `tile_edge_padding` to the `WarpedVRT` via the `SOURCE_EXTRA` keyword (see https://gdal.org/api/gdalwarp_cpp.html#structGDALWarpOptions). 

Before doing anything I'd love to know how you produced the image from your initial post https://github.com/cogeotiff/rio-tiler/issues/56#issuecomment-488920779

**Comment by rowanwins** [comment]
It was nothing too wild, I simply had a local version of rio-tiler running from which I requested two adjacent tiles with a get request and then wrote them to disk, I then stuck them next to each other in photoshop.

The effect was particularly pronounced on the data I was using which was a single band raster which had a range of -1 to 1.

Regarding moving to SOURCE_EXTRA I suspect you know far more about gdal than I do so I'm not sure I can contribute much useful thinking there, but happy to sanity check any results :)

**Comment by vincentsarago** [comment]
@rowanwins Thanks, I'll try to reproduce the test you did
