### ISSUE TITLE
Remove alpha band from output `tile` data when indexes is not passed

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#127]
in #126 , @pierotofy raised an issue about alpha band. 
When you have a RGBA input data, rio-tiler will return a 4 bands tile data + a mask but it means we have duplicate data between the 4th band and the mask.

When no `indexes` option is passed to `rio_tiler.utils.tile_read`, we could maybe remove the `alpha` band from the indexes tuple ?

**Comment by pierotofy** [comment]
Not sure if it's the right approach, but this is how I solved it:

```
if tile.shape[0] == 4:
    mask = None
```

Right after `main.tile`.

**Comment by vincentsarago** [comment]
@pierotofy that's really custom and we might need something `global` like 

```python
def non_alpha_indexes(src_dst):
    return [
       b for ix, b in enumerate(src_dst.indexes) if (src_dst.mask_flag_enums[ix] is not MaskFlags.alpha and src_dst.colorinterp[ix] is not ColorInterp.alpha)
    ]

with rasterio.open("my_rgba_file.tif") as src_dst:
    print(non_alpha_indexes(src_dst))

(1, 2, 3)
```

**Comment by vincentsarago** [comment]
I've added the function in #129 but we still need to define if we want to use it by default!
