### ISSUE TITLE
Passing "cutline" as warp_vrt_option

### ISSUE THREAD

**Issue by dorukozturk** [cogeotiff/rio-tiler#140]
Hi,

Thanks for the great library, really appreciate it. 

I am trying to clip an image with a geojson or wkt geometry as I am tiling. 

What would be the best way to do that? I can see there are multiple ways to do this.

1) Pass an option to main.tile:
```python
(..., warp_vrt_option={'cutline': some_wkt})
```

2) Pregenerate a vrt and write it to a temp location and give that path to main.tile.

Is it possible to go with option 1 since it is easier and more straightforward? I could not make option 1 work no matter what I did. 

Any thoughts?

**Comment by vincentsarago** [comment]
Hi @dorukozturk 
so you said you tried option 1 and it doesn't work right ? d

do you have example or code to share so I can see what's going on

**Comment by dorukozturk** [comment]
@vincentsarago Yes, I could not make option 1 work. 
Unfortunately I cannot share the code but I can share a snippet:
```python
from rio_tiler import main
from rio_tiler.utils import array_to_image

wkt = 'POLYGON ((-90.30740261077881 39.06327781401454, -90.30717194080353 39.06327781401454, -90.30717194080353 39.06345691759628, -90.30740261077881 39.06345691759628, -90.30740261077881 39.06327781401454))'
path = 'some/path/to/a/geotiff.tif' # Tiff is in WGS84 (EPSG:4326)
tile, mask = main.tile(path, x, y, z, 
    tilesize=256, 
    indexes=[1,2,3], 
    warp_vrt_option={
        'cutline': wkt
    }
)
buffer = array_to_image(tile, mask=mask)
```
When I do something like this, I don't get any tiles. 
Should the wkt be in web mercator coordinates? 
Without the cutline option all is well, I see the tiles. When I add that argument, I don't see anything on debug logs (I set rasterio logging to DEBUG) and I don't see any tiles.

**Comment by vincentsarago** [comment]
> Should the wkt be in web mercator coordinates?

yes (see GDAL docs)

> CUTLINE: This may contain the WKT geometry for a cutline. It will be converted into a geometry by GDALWarpOperation::Initialize() and assigned to the GDALWarpOptions hCutline field. The coordinates must be expressed in source pixel/line coordinates. Note: this is different from the assumptions made for the -cutline option of the gdalwarp utility !

Because we are creating tile using Web Mercator projection, rio-tiler uses WarpVRT (Virtual + warping) of your input file in web mercator projection. 

Let me know how it goes

**Comment by dorukozturk** [comment]
I tried passing 
```python
{'cutline': 'POLYGON ((-10052974.07 4730739.63, -10052948.4 4730739.63, -10052948.4 4730765.31, -10052974.07 4730765.31, -10052974.07 4730739.63))'}
```

still no luck. Maybe this is a rasterio question.

**Comment by dorukozturk** [comment]
Ok the following worked:

```
wkt='POLYGON ((4000 4000, 4000 8000, 8000 8000, 8000 4000, 4000 4000))'
```
so "cutline" requires pixel coordinates. I hope this issue helps other people :)

Thanks for your help and again thank you for the great library.

**Comment by vincentsarago** [comment]
🤦‍♂ I should have read the doc better too ;-) 

> The coordinates must be expressed in source pixel/line coordinates. 

Glad you succeed 🎉

**Comment by vincentsarago** [comment]
@dorukozturk 👋 , I totally forgot about this issue 🤦 
just a quick FYI we added some native function to work with cutline https://cogeotiff.github.io/rio-tiler/advanced/feature/

🙏

**Comment by dorukozturk** [comment]
@vincentsarago Thank you very much. This looks fantastic :)
