### ISSUE TITLE
expr syntax doesn't match docstring

### ISSUE THREAD

**Issue by phloem7** [cogeotiff/rio-tiler#146]
Tiny inconsistency: 

Docstring for `expr` calls for bands specified by 'B', but regex only matches 'b'.

https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/utils.py#L738

Suggestion to match both cases: `r"[bB](?P<bands>[0-9A]{1,2})"`

Happy to make PR, just let me know which case(s) should be used.

**Comment by vincentsarago** [comment]
hey @phloem7, 
That's sound really good and simple PR to do 😄 
I'll be happy to review it
