### ISSUE TITLE
AWS NAIP Imagery

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler#147]
Hello! This package looks amazing, and I'm excited to try setting up rio-tiler + lambda-tiler + rio-tiler-mosaic.

I see that there's default support for a few AWS public datasets, including Landsat/Sentinel. I'm interested in working with NAIP imagery, which is [also an AWS public dataset](https://registry.opendata.aws/naip/), and the visualization layer (`arn:aws:s3:::naip-visualization`) is in COG format.

I'm not sure yet exactly where to start, but would you be interested in a pull request to add default NAIP support? NAIP is U.S. only, but it has pretty high resolution (up to 0.6m) and has been taken a few times ([annual coverage map](https://www.arcgis.com/home/webmap/viewer.html?webmap=17944d45bbef42afb05a5652d7c28aa5)).

**Comment by vincentsarago** [comment]
Hi @kylebarron thanks for the nice words.

The support of Sentinel, Landsat and CBERS dataset is quite simple in this package and most of what it does is translate a `scene id` to an S3 Path (and also translate band to file names). But we don't do anything fancy. If NAIP is already in COG there is nothing we can do IMO. 

What we can do is maybe just add an example on the Readme showing how to use the NAIP imagery with rio-tiler ?
