### ISSUE TITLE
Bounds function

### ISSUE THREAD

**Issue by jaimebayes** [cogeotiff/rio-tiler#149]
Hi Vincent, 

Have you think to add functionality on importing image data from image path?, i mean, when you have complete Sentinel 2 image (all bands) in your colab or local directory, so you can use bounds function.
I try this:

`cd /gdrive/My Drive/Notebooks/data/S2C/

scene_id = 'T18NWL_20170404T153111_B03.jp2'

bounds = sentinel2.bounds(scene_id)`

but I got this error:
InvalidSentinelSceneId: Could not match T18NWL_20170404T153111_B03.jp2

Thanks in advance, JL

**Comment by vincentsarago** [comment]
Hi @jaimebayes 
the `rio_tiler.sentinel2` submodule is `ONLY` to access AWS Public Dataset. If you have local data you should use `rio_tiler.main` submodule.
