### ISSUE TITLE
Not being able to import main from rio-tiler

### ISSUE THREAD

**Issue by manishsharma28** [cogeotiff/rio-tiler#153]
**Not being able to import main from rio-tiler.**
**`import rio_tiler` is working fine.** 
**But `from rio_tiler import main as rt_main` is giving the following error:**

**Error:**
_CPLE_OpenFailedError                      Traceback (most recent call last)
rasterio\_crs.pyx in rasterio._crs._CRS.from_epsg()

rasterio\_err.pyx in rasterio._err.exc_wrap_int()

CPLE_OpenFailedError: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

During handling of the above exception, another exception occurred:

CRSError                                  Traceback (most recent call last)
<ipython-input-2-8e450ce7a136> in <module>
      1 import rio_tiler
----> 2 from rio_tiler import main as rt_main
      3 import mercantile
      4 
      5 from rasterio.transform import from_bounds

c:\users\ms\rio-tiler\rio_tiler\main.py in <module>
      5 from rasterio.warp import transform_bounds
      6 
----> 7 from rio_tiler import utils
      8 from rio_tiler.errors import TileOutsideBounds
      9 

c:\users\ms\rio-tiler\rio_tiler\utils.py in <module>
     87     max_size=1024,
     88     percentiles=(2, 98),
---> 89     dst_crs=CRS({"init": "EPSG:4326"}),
     90     histogram_bins=10,
     91     histogram_range=None,

~\Anaconda3\lib\site-packages\rasterio\crs.py in __init__(self, initialdata, **kwargs)
     68             data.update(**kwargs)
     69             data = {k: v for k, v in data.items() if k in all_proj_keys}
---> 70             self._crs = _CRS.from_dict(data)
     71 
     72         else:

rasterio\_crs.pyx in rasterio._crs._CRS.from_dict()

rasterio\_crs.pyx in rasterio._crs._CRS.from_epsg()

CRSError: The EPSG code is unknown. Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files._

**Comment by vincentsarago** [comment]
Hi @manishsharma28 thanks for the issue. 

I'm not an anaconda expert but the error message says you need to set GDAL_DATA env to you GDAL installation ... You can also try to set PROJ_LIB toward your libproj install. 

This is a anaconda/rasterio problem not a rio-tiler.
