### ISSUE TITLE
version 1

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#16]
We just published rio-tiler 1.0a0. 
This version includes some new features like:
- Landsat 8 Thermal bands support
- CBERS data Support 

Here are some next point I'd like to focus before releasing a final v1: 
- create mask inside the `tile` functions (instead of defining it in array_to_img). Basically the tile function would return a `tile data` and a `mask` which could be used in `array_to_img`. This will able to rescale data between 0 and 255 (instead of 1 -> 255, 0 being used as nodata).

- Automatic color correction instead of linear rescaling (using rio-color).

- better support for `main`(local or https)  and `s3` files.

**Comment by vincentsarago** [comment]
I think we could also remove https://github.com/mapbox/rio-tiler/blob/master/rio_tiler/aws.py and let the user use https://github.com/mapbox/rio-tiler/blob/master/rio_tiler/main.py. 

Basically, the only difference between `main.py` and `aws.py` is that `aws.py` is creating the `address` from a given bucket and key, but there is not need for such abstraction. any user could construct the s3 url and pass it to `main.py`.

**Comment by vincentsarago** [comment]
👋 Long time no see 👋 
I'm planning to pursue this and try to publish `1.0.0` at the end of next week 🎉

**Comment by samsammurphy** [comment]
Very cool! Really glad to see :tada:

**Comment by vincentsarago** [comment]
version `1.0rc3` is on pypi since Tuesday with all changes from #73. Still targeting Friday 8th for an official release 🎉

**Comment by vincentsarago** [comment]
🎉 https://pypi.org/project/rio-tiler/1.0.0/ Thanks everyone who's been following/helping. 

We can now move to higher plugin/module (e.g. mosaics, vectors ...)
