### ISSUE TITLE
Bug in new `calculate_default_transform` from terracotta

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#164]
While using the new `calculate_default_transform` from Terracotta seemed to help with the performance, I encountered a but when dealing with scene that crosses the dateline separation

![](https://user-images.githubusercontent.com/10407788/77132485-07cee800-6a36-11ea-8edb-a196decf25a3.png)

The problem happens here: https://github.com/cogeotiff/rio-tiler/blob/06504ec8321d185602a5a91bc6b5415bdb94915c/rio_tiler/utils.py#L232-L241

which will return `negative` width/height 

```
Tile
x=17
y=21
z=6

vrt_transfrom
|-386.76, 0.00,-9392582.04|
| 0.00, 6.31, 6887893.49|
| 0.00, 0.00, 1.00|

vrt_width=-1619
vrt_height=-99186
```

dataset link: https://www.dropbox.com/s/jyskcxqnbq3240c/ask_cog.tif?dl=0

Not sure if it means something but here is the result from both rasterio and terracotta's calculate_default_transform for a random tile.

```
# rasterio
| 238.34, 0.00,-20037508.08|
| 0.00,-238.34, 13596067.67|
| 0.00, 0.00, 1.00|

# terracotta
|-386.54, 0.00,-20028306.76|
| 0.00, 6.31, 13596067.67|
| 0.00, 0.00, 1.00|
```

@dionhaefner, could you test terracotta with the dataset I shared, so I can confirm this is only happening in rio-tiler ?

**Comment by dionhaefner** [comment]
Oops, sorry! We actually have an open issue for datasets spanning the date line, since we never tested it (and I suspected it wouldn't work):

https://github.com/DHI-GRAS/terracotta/issues/53

I'll see if I can fix it, thanks for the test data.

**Comment by dionhaefner** [comment]
Yikes, this image is pretty much the perfect storm for my method

<img width="501" alt="Screen Shot 2020-03-20 at 14 50 08" src="https://user-images.githubusercontent.com/11994217/77169625-19f26a00-6aba-11ea-9d48-a8001b766497.png">

- It is rotated so much that the top right corner is *further west* than the bottom left corner
- Only one corner of the raster crosses the date line
- Top left and bottom right corner of the image lie almost on the same latitude
- Bottom left and top right corner lie almost on the same longitude

In cases like these, we cannot possibly do better than GDAL's default transform. So even after I fix the bugs and catch these edge-cases, the result will not be better than the default.

I'll have to come up with a better way to solve this, in the meantime I suggest you revert to the default transform.

**Comment by vincentsarago** [comment]
thanks a lot @dionhaefner. 

I don't want to fall back totally to gdal/rasterio because your method works fine for other dataset. For now I think I'll try to add an edge case test and fall back only if I really need ;-)

**Comment by dionhaefner** [comment]
Sure. I suggest you test for the width and height returned by my method. If they are very different from the original image width and height, you know something went wrong.

**Comment by dionhaefner** [comment]
What would you think about the following workaround:

- Detect whether dataset crosses the dateline
- Compute the default transform with fake bounds that are shifted so the dataset doesn't cross the dateline anymore

This only works for target CRS that don't depend on longitude, like latlon or (web) Mercator.

Would you consider that too hacky?

**Comment by dionhaefner** [comment]
While investigating I found something weird (and troubling) with the way rio-tiler and Terracotta read tiles.

If I understand rio-tiler correctly, both projects read tiles like this:

1. Determine best resolution in target CRS.
2. Create VRT with that resolution that spans tile bounds (+ some optional padding).
3. Do decimated read from this VRT to resample to tile size.

I built our tile reader with the understanding that a higher resolved VRT would lead to a more accurate output tile, at the expense of having to consider more pixels during resampling. However, that seems to be *false*.

Look at the following output:

(all with nearest resampling)

### My new calculate_transform

#### VRT

![new-vrt](https://user-images.githubusercontent.com/11994217/77430718-e6764f00-6ddb-11ea-886f-27748c980175.png)


#### Resulting tile

![new-tile](https://user-images.githubusercontent.com/11994217/77430862-23424600-6ddc-11ea-855e-e99d7030c419.png)

### GDAL default transform

#### VRT

![old-vrt](https://user-images.githubusercontent.com/11994217/77430733-eb3b0300-6ddb-11ea-9f36-dd27f0dbffc9.png)

#### Resulting tile

![old-tile](https://user-images.githubusercontent.com/11994217/77430838-19204780-6ddc-11ea-9234-21a4703bae08.png)

---

It looks to me rasterio / GDAL is reading from the wrong overview when using the larger VRT. I can fix this behavior by correcting the target resolution after step 1 like this:

```python
# determine optimal overview level
overview_level = -1
src_res = dst_res[0]
target_res = abs(transform.from_bounds(*bounds, *tile_size).a)

if target_res > src_res:
    res = [src_res * decim for decim in src.overviews(1)]
    for overview_level in range(overview_level, len(res) - 1):
        ovrRes = src_res if overview_level < 0 else res[overview_level]
        nextRes = res[overview_level + 1]
        if (ovrRes < target_res) and (nextRes > target_res):
            break
        if abs(ovrRes - target_res) < 1e-1:
            break
    else:
        overview_level = len(res) - 1

if overview_level >= 0:
    decim = src.overviews(1)[overview_level]
    dst_res = (dst_res[0] * decim, dst_res[1] * decim)
```

You might recognize this as the code you wrote to force rasterio to read a specific overview. Note that I am *not* doing that; I just do the resolution correction you introduced. Could you give some more background on how you came up with that?

Tile after correction, which is now robust to changes in the target resolution:

![new-tile-corr](https://user-images.githubusercontent.com/11994217/77431308-cdba6900-6ddc-11ea-8538-050fc6e948c4.png)

**Comment by vincentsarago** [comment]
I spend hours on the `wrong overview` problem to finally find that rasterio was doing the right thing at least when using rasterio calculate_default_transform.

the overview calculation came from GDAL https://github.com/OSGeo/gdal/blob/41993f127e6e1669fbd9e944744b7c9b2bd6c400/gdal/apps/gdalwarp_lib.cpp#L2293-L2362 

I'm happy to jump on a call if you want. 

Note also there is some weird behaviour with resampling/overview and datatype: https://gist.github.com/vincentsarago/9951d1aab15359ee826b3b4c2cebeeab 

Maybe we don't use the right overview because the VRT size is not the same one we get with the gdal calculate_default_transform

**Comment by vincentsarago** [comment]
maybe I miss understood but are you suggesting to use the overview resolution directly in calculate_default_transform ?

**Comment by dionhaefner** [comment]
Yes, it seems like GDAL's default transform does more than I thought. But you can also see in the figures above that it leaves quite a bit of resolution on the table, which becomes evident at higher zoom levels:

**New**

![new-tile-corr-hizoom](https://user-images.githubusercontent.com/11994217/77438556-4245d580-6de6-11ea-9007-9e2e304034d8.png)

**GDAL**

![old-tile-hizoom](https://user-images.githubusercontent.com/11994217/77438571-4671f300-6de6-11ea-9b7f-76d3db8a7501.png)

**Comment by dionhaefner** [comment]
No, the algorithm that seems to work is:

```python
dst_res = (dst_transform.a, dst_transform.e)
# or anything you find appropriate, whether computed by default_transform or not

decim = get_overview_decim(...)
vrt_res = (decim * dst_res[0], decim * dst_res[1])
```

But I don't understand *why* it works.

**Comment by vincentsarago** [comment]
I don't get where the `vrt_res` is used then

**Comment by dionhaefner** [comment]
Sorry. Full algorithm looks like this:

```python
# this could be the default transform or any other function
dst_transform, _, _ = calc_transform(
    src.crs, target_crs, src.width, src.height, *src.bounds
)

# this is the resolution you think will represent the dataset best after reprojection
dst_res = (abs(dst_transform.a), abs(dst_transform.e))

# for some reason, this seems necessary to use the right overview
decim = get_overview_decimation_factor(src, dst_res, tile_bounds, tile_size)
vrt_res = (dst_res[0] * decim, dst_res[1] * decim)

# compute tile VRT shape and transform
vrt_width = max(1, round((tile_bounds[2] - tile_bounds[0]) / vrt_res[0]))
vrt_height = max(1, round((tile_bounds[3] - tile_bounds[1]) / vrt_res[1]))

vrt_transform = (
    transform.from_bounds(*tile_bounds, width=vrt_width, height=vrt_height)
)

# construct VRT
vrt = WarpedVRT(
    src, crs=target_crs, resampling=resampling_enum, add_alpha=True,
    transform=vrt_transform, width=vrt_width, height=vrt_height
)

# read
with vrt:
    tile_data = vrt.read(
        1, resampling=resampling_enum, out_shape=tile_size
    )
```

I understand that the VRT resolution should have an influence on which overview is being used if the VRT is coarse, but it doesn't make sense to me that I have to *increase* the pixel size / *lower* the resolution of the VRT for GDAL to select a *higher* resolved overview.

**Comment by dionhaefner** [comment]
I think I understand the problem now.

It is relatively easy to construct a transform that yields higher quality reprojections than GDAL's default transform. Just oversample the image a bit to make sure you don't lose any data.

This changes though when overviews are involved. If you oversample the image, *overviews are triggered earlier*, leading to an overall *degraded quality*. You can consider a situation where we duplicate every pixel at the VRT level:

```
112233
112233
445566
445566
```

If we then zoom out by a factor of 2, we would ideally see

```
123
456
```

But by then, the first overview is triggered already! So we actually see something like

```
13
46
```

As you noticed, trying to force GDAL to use a specific overview is a can of worms that I can't open at this point.

I suggest the following workaround:

```python
dst_transform, _, _ = rasterio.warp.calculate_default_transform(
    src.crs, target_crs, src.width, src.height, *src.bounds
)

tile_transform = transform.from_bounds(*tile_bounds, *tile_size)

dst_res = (
    min(abs(dst_transform.a), abs(tile_transform.a)),
    min(abs(dst_transform.e), abs(tile_transform.e)),
)
```

At low zoom levels, this uses the default transform, where it performs reasonably well. At high zoom levels, where we're at the pixel and sub-pixel level, it makes sure that the VRT always oversamples the tile, so we always get down to the true data density if we zoom far enough.

### Comparison

![ask-comparison](https://user-images.githubusercontent.com/11994217/77533560-644b6080-6e97-11ea-84e8-18f87c9b4345.png)

Performance difference is not above noise level.

**Comment by vincentsarago** [comment]
@dionhaefner Ti be honest I'm not sure I follow everything but I think you are telling me to switch back to the origin way to calculating the vrt_transform and size 
https://github.com/cogeotiff/rio-tiler/blob/6b0d4df0b6aa1454c50312e8d352ed57f0a4e3cb/rio_tiler/utils.py#L269-L310

?

**Comment by dionhaefner** [comment]
I suggest doing this:

https://github.com/DHI-GRAS/terracotta/blob/a200352a79808bf0a740777c64463999948bb03a/terracotta/drivers/raster_base.py#L447-L458

which is going live in Terracotta now. So you use GDAL's default transform for low zoom levels and the native tile transform for high zoom levels.

I recommend you *don't* use the default transform I wrote as it's based on faulty assumptions that do not hold when overviews are involved. If you saw performance improvements they are probably at the cost of reduced quality.

**Comment by vincentsarago** [comment]
I just ran a test switching back to the original method and I still see performance improvement which I think is mostly due to #166
