### ISSUE TITLE
Color ops bug with rio tiler v2

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler#173]
Switching to rio-tiler v2 caused color ops to fail when used with landsat imagery with `awspds-mosaic`.

Before:
![image](https://user-images.githubusercontent.com/15164633/79832112-f430dd00-8365-11ea-859b-266c5ed9ab93.png)

After:
![image](https://user-images.githubusercontent.com/15164633/79832107-ef6c2900-8365-11ea-8e24-24f962dc518f.png)

The easiest way to reproduce this is to deploy the `rio-tiler-v2` branch of `awspds-mosaic`:
```bash
git clone https://github.com/kylebarron/awspds-mosaic
cd awspds-mosaic
git checkout rio-tiler-v2
make package
cd services/landsat
sls deploy --bucket bucket

{ENDPOINT_URL}/production/tiles/8113f57876010a63aadacef4eac6d010d10c9aafcf36a5ece064ea7f/12/772/1607@2x.jpg?bands=4,3,2&color_ops=gamma+RGB+3.5%2C+sigmoidal+RGB+15+0.35%2C+saturation+1.7
```

I realize you can't access that on my bucket, so I've attached the source MosaicJSON in a zip file:
[8113f57876010a63aadacef4eac6d010d10c9aafcf36a5ece064ea7f.json.zip](https://github.com/cogeotiff/rio-tiler/files/4508038/8113f57876010a63aadacef4eac6d010d10c9aafcf36a5ece064ea7f.json.zip)

**Comment by kylebarron** [comment]
Testing with #174 made the color ops apply correctly.

**Comment by vincentsarago** [comment]
fixed in https://github.com/cogeotiff/rio-tiler/pull/174 and currently in V2 branch. 

The problem you are seing is that in rio-tiler==1.0 the landsat8.tile function was returning Uint16 data while the new rio-tiler=2.0a4 was returning float32. I reverted this because it should be Uint16.
