### ISSUE TITLE
Add `postprocess` callback

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#181]
Sometimes we want to apply post process on a tile (or data), like apply a custom rescaling.

We can easily achieve this by just wrapping the `tile` function: 

```python
from rio_tiler import reader

def my_tile(path, x, y, z):
    tile, master = reader.tile(path, x, y, z)

    return tile / 10000.0, mask
```

But when if you wanted to get the `metadata` of the same raster with your custom `process` added, you'll have to re-write the whole `rio_tiler.reader.metadata` function.

To overcome this we could *just* add a `postprocess: Callable` option in `rio_tiler.reader._read` function.

```python
def postprocess(arr: numpy.ndarray, mask: numpy.ndarray) -> Tuple[numpy.ndarray, numpy.ndarray]:
   
   arr = arr // 10000.0

   return arr, mask
```

Because `metadada`, `preview`, `part` and `tile` all use `_read` they will forward the `postprocess` function to `_read`.

```python
from rio_tiler import reader

with rasterio.open("my.tif") as src_dst:
     metadata = reader.metadata(src_dst, postprocess=postprocess)

```

Changes in `rio_tiler.reader._read`
```python
def _read(
    src_dst: Union[DatasetReader, DatasetWriter, WarpedVRT],
    height: int,
    width: int,
    indexes: Optional[Union[Sequence[int], int]] = None,
    out_window: Optional[Window] = None,
    nodata: Optional[Union[float, int, str]] = None,
    resampling_method: Resampling = "bilinear",
    force_binary_mask: bool = True,
    unscale: bool = False,
    vrt_options: Dict = {},
    postprocess: Optional[Callable] = None,
) -> Tuple[numpy.ndarray, numpy.ndarray]:

    if postprocess:
         return postprocess(data, mask)

    return data, mask
```

Question:
- How do we enfore `postprocess` callable to accept `data` and `mask` as minimum input ?
- How do we enfore `postprocess` callable to return only `data` and `mask`

**Comment by kylebarron** [comment]
I see you're warming to the idea of passing callable's 😉 .

Though I think you must want something more in your callable's arguments.
```py
def postprocess(arr: numpy.ndarray, mask: numpy.ndarray) -> Tuple[numpy.ndarray, numpy.ndarray]:
```
That alone presents no extra information to `postprocess`. Are you thinking a signature like 
```py
def postprocess(arr: numpy.ndarray, mask: numpy.ndarray, src_dst: rasterio dataset)
```
?

**Comment by vincentsarago** [comment]
hey @kylebarron thanks for jumping on this ;-) 

> I see you're warming to the idea of passing callable's 😉.

I guess I'll have to add a note where I say you inspired me ;-) 

My main motivation for the `callback` was for Landsat data where we have to do the TOA calibration after reading so I though that I could do 

```python

from rio_tiler import reader

def _convert(arr: numpy.ndarray, mask: numpy.ndarray, band: str, metadata: Dict) -> numpy.ndarray:
    """Convert DN to TOA or Temp."""
        multi_reflect = metadata["RADIOMETRIC_RESCALING"].get(
            f"REFLECTANCE_MULT_BAND_{band}"
        )
        add_reflect = metadata["RADIOMETRIC_RESCALING"].get(
            f"REFLECTANCE_ADD_BAND_{band}"
        )
        sun_elev = metadata["IMAGE_ATTRIBUTES"]["SUN_ELEVATION"]

        arr = 10000 * reflectance.reflectance(
            arr, multi_reflect, add_reflect, sun_elev, src_nodata=0
        )
    return arr, mask

cb = partial(_convert, "B1", metadata)
with rasterio.open("B1.tif") as src_dst:
    tile, mask = reader.tile(src_dst, 1, 1, 1, callback=cb)
```

**Comment by kylebarron** [comment]
Interesting approach. I'd still argue that example is quite confusing and doesn't support the case for adding the `postprocess` callback. After all, isn't that identical to

```py
with rasterio.open("B1.tif") as src_dst:
    tile, mask = reader.tile(src_dst, 1, 1, 1)
	tile, mask = _convert(tile, mask, "B1", metadata)
```
Specifically, the extra information you're using for this postprocess callback is coming from _outside_ the function. The reason for adding it inside `reader.tile` is if there's information within `reader.tile` that you can't access from outside it.
