### ISSUE TITLE
Why does image appear less sharp compared with that viewed in QGIS?

### ISSUE THREAD

**Issue by qAp** [cogeotiff/rio-tiler#194]
Hi
Thanks for these very handy tools to work with large image files.  I'm kind of new to this and am wondering if I've misunderstood how images are rendered in different places.  

If I open the original tif file (which is not a valid cog) in QGIS and zoom onto the area of interest.  It looks like this (screenshot):
<a href="https://imgur.com/zGaeesY"><img src="https://i.imgur.com/zGaeesY.png" title="source: imgur.com" /></a>

If I use `rio-cogeo` to convert it into a COG with:
```
rio cogeo create '{str(path_in)}' out_jpeg.tif -b 1,2,3 --add-mask --cog-profile jpeg
```
and then grab the corresponding tile with
```
tile, mask = rt_main.tile('out_jpeg.tif', *tiles.iloc[idx].xyz, tilesize=1024)
tile = tile.transpose([1, 2, 0])
_, ax = plt.subplots(figsize=(8, 8))
ax.imshow(tile, interpolation='none')
ax.axis('off');
```
, I see an image like this (screenshot), which seems slightly blurry, or to have softer lines, compared with what's seen in QGIS:
<a href="https://imgur.com/KR3IBPC"><img src="https://i.imgur.com/KR3IBPC.png" title="source: imgur.com" /></a>

Has the original image become less sharp going through `rio-cogeo` and `rio-tiler`, or it's just QGIS doing some processing to make the image appear very sharp?    If the former, ere there some optional arguments that can be specified in either `rio-cogeo` or `rio-tiler` to preserve the original image resolution?

Thanks

**Comment by vincentsarago** [comment]
Hi @qAp, thanks for the issue.

is your input GTIFF (`{str(path_in)}`) using JPEG compression too?, if not, this will be the cause. JPEG compression is NOT lossless, meaning you'll get a really light file but you'll loose some information (add blur). 

When displaying the file at low resolution QGIS will do nearest resampling which is also the default for creating the overview in rio-cogeo. I think there is an option i rio-cogeo `--overview-resampling` that let you change this to `bilinear`. This might also make the overview a bit less blurry

**Comment by qAp** [comment]
Can't actually tell the type compression of the tif file `{str(path_in)}` using either `file` or `identify`.  Does this mean there is something unusual about this tif file?  

I have tried various different `--overview-resampling` values and `--cog-profile` values, like `lzw`, but the quality of the subsequent tile time seems to be unchanged from before.  

Using `gdal` like this
```
ds = gdal.Open(os.path.join(path,filename))
    band = ds.GetRasterBand(1)
    xsize = band.XSize
    ysize = band.YSize

for i in range(0, xsize, tile_size_x):
        for j in range(0, ysize, tile_size_y):
            com_string = "gdal_translate -of JPEG -srcwin " + str(i)+ ", " + str(j) + ", " + str(tile_size_x) + ", " + str(tile_size_y) + " " + f'\"{os.path.join(path,filename)}\"' + " " + f'\"{os.path.join(out_path, output_filename + str(i) + "_" + str(j) + ".jpeg" )}\"'
            os.system(com_string)
```
yields tile images like this:

<a href="https://imgur.com/ZOwHb1s"><img src="https://i.imgur.com/ZOwHb1s.png" title="source: imgur.com" /></a>

whereas similar building structures using `rio-cogeo` and `rio-tiler` look like

<a href="https://imgur.com/O6brjEF"><img src="https://i.imgur.com/O6brjEF.png" title="source: imgur.com" /></a>

which seems more blurry (but maybe I'm splitting hairs here.)

**Comment by vincentsarago** [comment]
@qAp did you figure this out ?
