### ISSUE TITLE
[STAC] resolves relative asset path

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#212]
ref: https://github.com/developmentseed/titiler/issues/36#issue-639793489

from @fabricebrito 
> This feature would ease our setup as the STAC catalogues we use move from a location to another and this is why we use relative hrefs also for the asset paths. For instance pystac resolves the the full href with e.g.
```python
item.assets['nbr'].get_absolute_href()
```

**Comment by vincentsarago** [comment]
it should append here https://github.com/cogeotiff/rio-tiler/blob/ce156bc5aaa52c579ee0891998eef7a97e44469c/rio_tiler/io/stac.py#L184-L190

**Comment by emmanuelmathot** [comment]
Is there progress on this issue?

**Comment by vincentsarago** [comment]
@emmanuelmathot no, mostly because I have no idea how to do it 🤷‍♂️, I've looked at pystac but got lost!

**Comment by emmanuelmathot** [comment]
No problem, I modified the STACReader to use pystac. PR#313
