### ISSUE TITLE
Landsat8 time out

### ISSUE THREAD

**Issue by Gundisalv** [cogeotiff/rio-tiler#223]
Hello, first of all thanks for this great code!, now to the point, I am trying to test a Landsat8 tile, but keep getting a time out error.
`rasterio.errors.RasterioIOError: Connection timed out after 1001 milliseconds`
I guess that I am missing some configuration, I tried running it like `with rasterio.Env(aws_session):` but it did not work.

Any thoughts?

Kind regards,

Gonzalo

**Comment by kylebarron** [comment]
You might want to try turning off threading. See: https://github.com/mapbox/rasterio/issues/1828#issuecomment-552855809

These are my environment variables:
```
```

**Comment by Gundisalv** [comment]
Thanks for the response, I'll check it out!
