### ISSUE TITLE
Writing numpy array to cogs?

### ISSUE THREAD

**Issue by purijs** [cogeotiff/rio-tiler#245]
Is there a way to write a numpy array read using `rio-tiler` back to a cog file?

For eg, exporting the numpy array from `part()` method to a geo-referenced cog

**Comment by geospatial-jeff** [comment]
:wave:  I've done this recently!  You can save the numpy array to a [rasterio in-memory file](https://rasterio.readthedocs.io/en/latest/topics/memory-files.html) and pass the file handle as the source argument to [`rio_cogeo.cog_translate`](https://github.com/cogeotiff/rio-cogeo/blob/master/rio_cogeo/cogeo.py#L42-L61.  There is a good example of this [here](https://github.com/cogeotiff/rio-cogeo#using-the-api-with-in-memoryfile).

**Comment by purijs** [comment]
> 👋 I've done this recently! You can save the numpy array to a [rasterio in-memory file](https://rasterio.readthedocs.io/en/latest/topics/memory-files.html) and pass the file handle as the source argument to [`rio_cogeo.cog_translate`](https://github.com/cogeotiff/rio-cogeo/blob/master/rio_cogeo/cogeo.py#L42-L61). There is a good example of this [here](https://github.com/cogeotiff/rio-cogeo#using-the-api-with-in-memoryfile).

In "Using the API with in MemoryFile" section:

What is `dst_transform` in `transform=dst_transform` ?

**Comment by vincentsarago** [comment]
@purijs the `dst_transform` is the transform information for the GeoTIFF (origin, resolution). From the rio-cogeo doc example
```
# Create GeoTIFF profile
bounds = mercantile.bounds(mercantile.Tile(0,0,0))
src_transform = from_bounds(*bounds, 1024 1024)
```

the transform is created using rasterio helper function (from_bounds) by passing the bounds of the data and the height and width.

I think with this we are good to close. Feel free to reopen if there is a proper bug 🙏
