### ISSUE TITLE
Cloud mask pixel selection for mosaics

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler#252]
It would be nice to be able to do simple cloud masking for mosaic pixel selection. I.e. use Landsat's QA band and return the pixel with the lowest cloud cover of the input assets.

To do this, however, you need to add more parameters to `pixel_selection.feed`, such as the asset id, because you need a way to keep track of which data array has which cloud mask.

**Comment by vincentsarago** [comment]
> To do this, however, you need to add more parameters to pixel_selection.feed, such as the asset id, because you need a way to keep track of which data array has which cloud mask.

can we just need to add `**kwargs` to the `feed` abstractmethod?

**Comment by vincentsarago** [comment]
@kylebarron for the use case you mentioned, we specifically use https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/mosaic/methods/defaults.py#L160 pixel_selection method. 

```python
img = scene.tile(x, y, z bands=("B1", "B2", "BQA"), pixel_selection=LastBandLow) 
print(img.count)
>>> 2
```

The magic trick in `LastBandLow` is that it will remove the `last` band from the array when returning the data.


Feel free to re-open if you see more needs!

**Comment by kylebarron** [comment]
That's pretty smart!
