### ISSUE TITLE
fix actions for publish

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#317]
https://github.com/cogeotiff/rio-tiler/blob/f87bdb68b84457ddf7d918a7f760929c4f6a6ac6/.github/workflows/ci.yml#L4-L8

without the `tags` event the publish job won't be run I think.

ref: https://github.com/developmentseed/tilebench/blob/master/.github/workflows/ci.yml#L4-L10

cc @kylebarron ;-)

**Comment by vincentsarago** [comment]
closed in https://github.com/cogeotiff/rio-tiler/commit/576c93b82bb9d033f38dc79ef305b71a2c8ca44e

**Comment by kylebarron** [comment]
This is the same as before my change! The publish always required tags!
