### ISSUE TITLE
Check if transform is ok

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#338]
first mentioned in https://github.com/cogeotiff/rio-cogeo/issues/164

I'm seeing some weird Internal Tile fetching behavior. When working with a Web Mercator aligned file I would expect GDAL to only do 2 GET requests (header + tile) but It seems that we are fetching more than 1 tile.

```
$ tilebench profile https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif --tile 5-10-9 --add-kernels | jq
{
  "LIST": {
    "count": 0
  },
  "HEAD": {
    "count": 1
  },
  "GET": {
    "count": 3,
    "bytes": 17144,
    "ranges": [
      "0-16383",
      "205900-206279",
      "242386-242765"
    ]
  },
  "WarpKernels": [
    [
      "Src=512,2303,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2431,257x129",
      "Dst=0,128,256x128"
    ]
  ],
  "Timing": 0.4853549003601074
}
```

☝️ we do 3 GET, 
```
[
      "0-16383",  <-- GeoTIFF Header
      "205900-206279",  <--- Tile Data
      "242386-242765".  <--- Tile Data
]
```

The weird part is when we look at the WarpKernels:

```
[
    [
      "Src=512,2303,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2431,257x129",
      "Dst=0,128,256x128"
    ]
]
```

I'm not sure how to read the Kernels but the `257x129` seems weird.

For the particular tile 5-10-9, here are the WarpedVRT info

```
{
    'add_alpha': True, 
    'resampling': <Resampling.nearest: 0>, 
    'crs': CRS.from_epsg(3857), 
    'transform': Affine(2445.984905125635, 0.0, -7514065.6285459455, 0.0, -2445.984905125635, 8766409.89997027), 
    'width': 512, 
    'height': 512
}
Window(col_off=0, row_off=0, width=512, height=512)
(3, 256, 256)
```

The VRT is 512x512 for a 256x256 tile, which is what we expect because the zoom 5 correspond to the first overview.

The input and output size are ok, so maybe we need to check if the `transform` is aligned with the internal tiles. 
https://github.com/cogeotiff/rio-tiler/blob/4bd9be5db98827e40d4222627c3af59e9063bd95/rio_tiler/utils.py#L166-L182

**Comment by geospatial-jeff** [comment]
What versions are you using?

**Comment by vincentsarago** [comment]
@geospatial-jeff version of ?

**Comment by kylebarron** [comment]
Probably GDAL?

**Comment by vincentsarago** [comment]
GDAL 3.2, rasterio 1.2.0

**Comment by geospatial-jeff** [comment]
Taking a look at this with aiocogeo, those two particular GET requests are the 130th and 146th tile offset in the IFD.  The first overview is 16x16 tiles (8192 / 512), which means the additional tile is one row down (`5/10/10`).  You can see the same behavior with other requests (ignore the HEAD requests).

```
$ tilebench profile https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif --tile 5-10-10 --add-kernels | jq

{
  "LIST": {
    "count": 1
  },
  "HEAD": {
    "count": 8
  },
  "GET": {
    "count": 11,
    "bytes": 17144,
    "ranges": [
      "0-16383",
      "242386-242765",
      "270360-270739"
    ]
  },
  "WarpKernels": [
    [
      "Src=512,2559,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2687,257x129",
      "Dst=0,128,256x128"
    ]
  ],
  "Timing": 4.101164102554321
}
```

Same story but with the 146th and 162nd offset.  I think this is probably a rounding issue when the VRT transform, not sure if its because how rio-tiler is creating the transform, how GDAL is interpreting/applying it, or because of the file itself.

Given that the origin of the image is top left, and [GDAL uses the length of the diagonal to determine file size](https://gdal.org/api/gdal_alg.html#_CPPv423GDALSuggestedWarpOutput12GDALDatasetH19GDALTransformerFuncPvPdPiPi) on warping operations, we would expect to see rounding errors manifest in the bottom/right of the image which maybe explains why we consistently request an additional tile one row below the intended tile.  But we also aren't really defining any warp operations here because the VRT aligns with an internal block so there really isn't any warping to be done.

Maybe it is the file.  I'm pretty confident that aiocogeo can do web-aligned reads in one request if the image is aligned properly:

```python
import asyncio
import json

import mercantile
from aiocogeo.cog import COGReader

async def main():
    async with COGReader("https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif") as cog:
        tile = mercantile.Tile(10, 9, 5)
        bounds = mercantile.xy_bounds(tile)
        await cog.read(bounds=bounds, shape=(256, 256))
        print(json.dumps(cog.requests))

asyncio.run(main())
```

```
>>> {"count": 5, "byte_count": 17105, "ranges": [[0, 16384], [242390, 242569], [270364, 270543], [270552, 270731], [242578, 242757]], "header_size": 16385}
```

**Comment by vincentsarago** [comment]
FYI I'm getting the same result with a file created using GDAL COG driver

```
$ tilebench profile https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256px_COG.tif  --tile 5-10-9 --add-kernels | jq 
{
  "LIST": {
    "count": 0
  },
  "HEAD": {
    "count": 1
  },
  "GET": {
    "count": 4,
    "bytes": 81920,
    "ranges": [
      "0-16383",
      "16384-49151",
      "376832-393215",
      "425984-442367"
    ]
  },
  "WarpKernels": [
    [
      "Src=512,2304,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2432,257x129",
      "Dst=0,128,256x128"
    ]
  ],
  "Timing": 0.7137670516967773
}
```

**Comment by vincentsarago** [comment]
Alright I think I've find something. I totally forget but GDAL `GDALWarpOptions` has `SOURCE_EXTRA` (set to 1 by default).

> SOURCE_EXTRA: This is a number of extra pixels added around the source window for a given request, and by default it is 1 to take care of rounding error. Setting this larger will increase the amount of data that needs to be read, but can avoid missing source data.

ref: https://gdal.org/api/gdalwarp_cpp.html?highlight=vrt#_CPPv415GDALWarpOptions

BUT 

when overwriding source_extra=0 (using vrt_options in `.tile()`) this has no impact, and looking at the WarpKernels, I'll tend to conclude that SOURCE_EXTRA is already set to 0

```
# default
[
    [
      "Src=512,2303,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2431,257x129",
      "Dst=0,128,256x128"
    ]
]

# source_extra=0
[
    [
      "Src=512,2303,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2431,257x129",
      "Dst=0,128,256x128"
    ]
]

# source_extra=1
[
    [
      "Src=511,2302,259x131",
      "Dst=0,0,256x128"
    ],
    [
      "Src=511,2430,259x131",
      "Dst=0,128,256x128"
    ]
]

#source_extra=-1
[
    [
      "Src=513,2304,255x127",
      "Dst=0,0,256x128"
    ],
    [
      "Src=513,2432,255x127",
      "Dst=0,128,256x128"
    ]
]
```

**Comment by vincentsarago** [comment]
Trying to replicate rio-tiler command with gdalwarp: 

```
$ bash-4.2# gdalwarp -overwrite -q \
>     /vsicurl/https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif \
>     out.tif \
>     -te -7514065.6285459455 7514065.6285459455 -6261721.35712162 8766409.89997027 \
>     -t_srs EPSG:3857 \
>     -ts 256 256 \
>     -r near \
>     -ovr 0 \
>     --config CPL_DEBUG ON --config GDAL_DISABLE_READDIR_ON_OPEN EMPTY_DIR

HTTP: libcurl/7.73.0 OpenSSL/1.0.2k-fips zlib/1.2.7 nghttp2/1.42.0
VSICURL: GetFileSize(https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif)=1349486  response_code=200
VSICURL: Downloading 0-16383 (https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif)...
VSICURL: Got response_code=206
GDAL: GDALOpen(/vsicurl/https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif, this=0xf763a0) 
GDAL: Using GTiff driver
GDAL: Computing area of interest: -90, -2.67167e-13, 90, 85.0511
...
GDAL: GDALDriver::Create(GTiff,out.tif,256,256,3,Byte,0xf77060)
...
WARP: Selecting overview level 0 for /vsicurl/https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif
...
GDAL: Computing area of interest: -90, -2.67167e-13, 90, 85.0511
VSICURL: Downloading 205900-206279 (https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif)...
VSICURL: Downloading 242386-242765 (https://rio-tiler-dev.s3.amazonaws.com/data/eu_webAligned_256pxWEBP.tif)...
...
GDAL: GDALWarpKernel()::GWKNearestNoMasksOrDstDensityOnlyByte() Src=512,2303,257x257 Dst=0,0,256x256
...
```

Notes:
- for an unknown reason I had to force using overview=0 to get the same blocks

Note on the WarpKernels
```
# rasterio
[
    [
      "Src=512,2303,257x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=512,2431,257x129",
      "Dst=0,128,256x128"
    ]
]

# gdal
Src=512,2303,257x257 Dst=0,0,256x256
```
They are both the same, except in rasterio we split the block in 2 (2 x 128). 

if we decode the kernels 
x = 512
y = 2303 **!** <--- it should be 2304 (9x256)

so here we have a difference in the Y coordinates.

**Comment by vincentsarago** [comment]
Stil trying to get a sense of what is going on: https://gist.github.com/vincentsarago/1bc5b2f8e884594f640a109589a271af

I'm pretty sure it all comes down to precision issues. GDAL and Mercantile don't use the same TMS definition (origin/res are different): 

```
GDAL:        20037508.342789244
Morecantile: 20037508.3427892
```

And thus the tile bounds and internal block bounds don't align perfectly 
```
# internal block (x=3, y=9, z=1)
COG:                [-7514065.628545967, 7514065.628545967, -6261721.357121639, 8766409.899970295]
rio-COG:            [-7514065.628545957, 7514065.628545931, -6261721.35712163, 8766409.899970258]
# tms tile (x=10, y=9, z=5)
morecantile bouds:  [-7514065.6285459455, 7514065.6285459455, -6261721.35712162, 8766409.89997027]
mercantile bouds:   [-7514065.628545966, 7514065.628545967, -6261721.357121638, 8766409.899970295]

diff between mercantile and GDAL block
[-9.313225746154785e-10, 0.0, -9.313225746154785e-10, 0.0]

diff between morecantile and GDAL block
[-2.1420419216156006e-08, 2.1420419216156006e-08, -1.862645149230957e-08, 2.421438694000244e-08]

diff between morecantile and rio-cogeo block
[-1.1175870895385742e-08, -1.4901161193847656e-08, -9.313225746154785e-09, -1.30385160446167e-08]
```

**Comment by vincentsarago** [comment]
as mentioned in #345 the precision errors in the `bounds` results in *errors* in the windows which then makes GDAL/Rasterio query more blocks than needed
