### ISSUE TITLE
Use importlib.resources to load colormap files

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler#340]
We currently use `__file__` to get the path of files inside the Python module.
https://github.com/cogeotiff/rio-tiler/blob/4bd9be5db98827e40d4222627c3af59e9063bd95/rio_tiler/colormap.py#L14-L17

This [does not always work](https://stackoverflow.com/a/779552):

> This will not work if the files are in a distribution (IE. egg). Use pkg_resources to get at the data file

Historically the workaround was to use `pkg_resources`, however as we know this is very slow. I just learned that there's a new, more performant way to reliably access package data: [`importlib.resources`](https://docs.python.org/3/library/importlib.html#module-importlib.resources). That was added in Python 3.7, but there's [a backported library](https://pypi.org/project/importlib-resources/) for earlier versions.

So you can import with:

```py
try:
    import importlib.resources as pkg_resources
except ImportError:
    # Try backported to PY<37 `importlib_resources`.
    import importlib_resources as pkg_resources
```

E.g.

```py
import importlib.resources
import rio_tiler
print(importlib.resources.read_text(rio_tiler, 'reader.py'))
# """rio-tiler.reader: image utility functions."""
# ...
```

See [this very good SO answer](https://stackoverflow.com/a/20885799) for more info. We could probably also use this in other places. Where else do we have local package data? Titiler?

**Comment by vincentsarago** [comment]
🎉 

> See this very good SO answer for more info. We could probably also use this in other places. Where else do we have local package data? Titiler?

morecantile
titiler
rio-viz
cogeo-mosaic-plugins
... 

😬

**Comment by kylebarron** [comment]
> To access a file inside the current module, set the package argument to `__package__`, e.g. `pkg_resources.read_text(__package__, 'temp_file')`

👀

**Comment by vincentsarago** [comment]
@kylebarron not sure what the previous message is about
