### ISSUE TITLE
how I can get metadata with expr

### ISSUE THREAD

**Issue by githubhanjunjun** [cogeotiff/rio-tiler#358]
## coding
v1.0
with rasterio.open('xx.tif', "r") as src:
    info = main.metadata(src, pmin=pmin, pmax=pmax, histogram_bins=255, histogram_range=hrange, expr=expr, nodata=nodata)
v2.0
with COGReader('xx.tif') as cog:
    meta = cog.metadata(pmin=pmin, pmax=pmax, hist_options=dict(bins=255, range=hrange), nodata=nodata)
## The problem
 I can't set expr parameter in v2.0 version，how I can get metadata with expr

**Comment by vincentsarago** [comment]
@githubhanjunjun I don't remember that `expr` was possible in V1 

we decided to not add expression in V2 for the metadata method but there are ways to do it 

```python
from rio_tiler.io import COGReader
from rio_tiler.utils import _stats as raster_stats

from rio_tiler.models import ImageStatistics, Metadata


with COGReader("xx.tif") as cog:
    data, mask = cog.preview(expression=expression)
    data = numpy.ma.array(data)
    data.mask = mask == 0

    expression_bloc = expression.lower().split(",")
    
    stats = {
        f"{expression_bloc[b]}": raster_stats(data[b], percentiles=(2, 98))
        for b in range(data.shape[0])
    }
    stats = {b: ImageStatistics(**s) for b, s in stats.items()}

    return Metadata(statistics=stats, **cog.info().dict())
```

please feel free to close this issues if ☝️ does the trick for you

**Comment by vincentsarago** [comment]
closing this, feel free to reopen if ☝️ is not enough

**Comment by githubhanjunjun** [comment]
Thank you very much for your reply

**Comment by githubhanjunjun** [comment]
Thank you very much for your reply
