### ISSUE TITLE
hwo to use custom color_map?

### ISSUE THREAD

**Issue by GiHeart** [cogeotiff/rio-tiler#382]
Hello,In source code, I see that color_map is saved as a numpy array，Now，I want to make a new np array with my color_map,how to?color map like this:

mapplotlib.colors:
col.LinearSegmentedColormap.from_list('gndvi', ['#422112', '#724C01', '#CEA712', '#FFA904', '#FDFE00',
                                                        '#E6EC06', '#BACF00',
                                                        '#8BB001', '#72A002', '#5B8D03', '#448102', '#2C7001',
                                                        '#176100', '#035201'], 256)

**Comment by vincentsarago** [comment]
👋 @GiHeart 

Colormap used in [`rio_tiler.utils.render`](https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/utils.py#L303) (or`ImageData.render`) has to be a dictionary in form of:

```python
{
    0: [R, G, B, Alpha],
    1: [R, G, B, Alpha],
    2: ...
}
```

## From Matplotlib to rio-tiler format

```python
import matplotlib
import numpy

gndvi = matplotlib.colors.LinearSegmentedColormap.from_list(
    'gndvi', [
        '#422112',
        '#724C01',
        '#CEA712',
        '#FFA904',
        '#FDFE00',
        '#E6EC06',
        '#BACF00',
        '#8BB001',
        '#72A002',
        '#5B8D03',
        '#448102',
        '#2C7001',
        '#176100',
        # '#35201'   <--- this one is not valid
    ],
    256,
)

x = numpy.linspace(0, 1, 256)
cmap_vals = gndvi(x)[:, :]
cmap_uint8 = (cmap_vals * 255).astype('uint8')

# Choice 1 - save as binary 
numpy.save(f'gndvi.npy', cmap_uint8)


# Choice 2 - create a dict 
gndvi_dict = {idx: value.tolist() for idx, value in enumerate(cmap_uint8)}
```

## Register

Once you have either a numpy binary or the colormap as dict you can register it with the other default colormaps
```python
from rio_tiler.colormap import cmap

cmap = cmap.register({"mycustomcolormap": {colormap dict} or "path to your numpy file"}
``` 

If you save the colormap as numpy binary, you can add it to a specific directory in your environment and then tell rio-tiler to search for `.npy` files there by using `COLORMAP_DIRECTORY` environment variable.

https://github.com/cogeotiff/rio-tiler/blob/56f50abdd06a4f03a18ee1e63c0db233c474fffe/rio_tiler/colormap.py#L31-L35


I'll update https://cogeotiff.github.io/rio-tiler/colormap/ to cover ☝️

**Comment by GiHeart** [comment]
Thank you for your detailed answer, this is a great project！
