### ISSUE TITLE
Resource Authorization manager

### ISSUE THREAD

**Issue by emmanuelmathot** [cogeotiff/rio-tiler#397]
## Context
In titiler, we often need to access protected resources (basic auth, JWT, cookies...). In our current setup, we use a mix of environement variables such as `GDAL_HTTP_AUTH`, `GDAL_HTTP_USERPWD` for cog I/O and netrc files for python requests (stac I/O). This is not very easy to maintain and we are currently limited to HTTP basic authentication with a unique user.

## Issue Description
Design and implement a possible homogeneous mechanism to authenticate requests to protected resources
Currently identified remote resource access:
### COG servers via gdal /vsicurl/ driver
GDAL /vsicurl/ configuration is not super flexible for setting dynamically HTTP headers but it seems to have some options such as GDAL_HTTP_HEADER_FILE

### STAC catalogs using python requests lib
This one is easier since the requests lib allows all HTTP settings

Maybe there is already a mechanism I missed. Let me know

**Comment by vincentsarago** [comment]
@emmanuelmathot I'm not sure to understand your issue. Do you want to access the `request` when we fetch the STAC item in https://github.com/cogeotiff/rio-tiler/blob/61a310f551f0b525109626e0a7d80dd27311d81b/rio_tiler/io/stac.py#L168-L170 ?

**Comment by emmanuelmathot** [comment]
Yes, the credentials mechanism would be designed to apply authorization for fetching the STAC item (in this case the `request`)

**Comment by vincentsarago** [comment]
@emmanuelmathot I think we should add a `client_options`[here](https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/io/stac.py#L165) in STACReader, which will be forwarded to the [`fetch`](https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/io/stac.py#L33-L57) function. 

Note the client_options should be passed to `aws_get_object` and `request`
