### ISSUE TITLE
Percent should be percent

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#398]
in 
https://github.com/cogeotiff/rio-tiler/blob/61a310f551f0b525109626e0a7d80dd27311d81b/rio_tiler/utils.py#L86

the returned value is between 0 -> 1 while it should be a percent (0 -> 100)

**Comment by djimee** [comment]
I will fix this

**Comment by param-thakker** [comment]
Hi @vincentsarago, is this still open?

**Comment by geospatial-jeff** [comment]
@param-thakker it is, please go ahead!

**Comment by param-thakker** [comment]
@geospatial-jeff I have opened a pull request for this. Please review it and let me know if something more needs to be done.
