### ISSUE TITLE
Is it possible to generate a list of all tiles contained within a COG?

### ISSUE THREAD

**Issue by gastoneb** [cogeotiff/rio-tiler#412]
I see we can call `img = image.tile(x, y, z)`, which is fantastic. Does anyone know if we can pre-determine the set of zxy pairs that actually contain valid data within a COG? I remember in gdal2tiles.py there was something similar, with the `tile_details` and `tile_job_info` objects.

**Comment by vincentsarago** [comment]
```python
with COGReader("cog.tif") as cog:
    tiles = list(cog.tms.tiles(*cog.bounds, cog.maxzoom))
```
This will return all tiles covering the bounds of the COG

**Comment by gastoneb** [comment]
Very slick. Thank you!
