### ISSUE TITLE
error when reading a file

### ISSUE THREAD

**Issue by nes123** [cogeotiff/rio-tiler#450]
Hello, i have a tiff file that i can open with rasterio.

But i get the following error with COGReader:

File "/usr/local/lib/python3.9/site-packages/rio_tiler/io/cogeo.py", line 101, in __attrs_post_init__
    self.nodata = self.nodata if self.nodata is not None else self.dataset.nodata
AttributeError: '_GeneratorContextManager' object has no attribute 'nodata'

**Comment by nes123** [comment]
with rasterio.open(blob_in_bytes) as src:
    print(src.profile)

results in this output:

{'driver': 'GTiff', 'dtype': 'uint16', 'nodata': 0.0, 'width': 590, 'height': 1478, 'count': 4, 'crs': CRS.from_epsg(32610), 'transform': Affine(3.0, 0.0, 540492.0,
       0.0, -3.0, 4185945.0), 'blockxsize': 256, 'blockysize': 256, 'tiled': True, 'compress': 'lzw', 'interleave': 'pixel'}

**Comment by kylebarron** [comment]
What version of `rio-tiler` are you using?

**Comment by nes123** [comment]
rio-tiler-2.1.4

**Comment by kylebarron** [comment]
Can you provide a reproducible example? You haven't even told us what command you're running. It's likely because the `dataset` attribute is something unexpected.

**Comment by nes123** [comment]
I am reading from google storage:

bucket = client.bucket("bucket_name")
blob = bucket.blob(path-in-bucket)
blob_in_bytes = io.BytesIO(blob)
with COGReader(blob_in_bytes) as image:
    print(image.dataset)

**Comment by kylebarron** [comment]
Refer to the [`COGReader` documentation](https://cogeotiff.github.io/rio-tiler/api/rio_tiler/io/cogeo/#cogreader) on how to use it. Is `blob_in_bytes` actually the bytes of the file? I doubt it... `bucket.blob` I think references the file but doesn't download it. And the first argument of `COGReader` is `input`, which is "Cloud Optimized GeoTIFF path.". Alternatively you could provide a `dataset` argument with a `rasterio` dataset, but a blob is not a dataset.

**Comment by kylebarron** [comment]
You should be able to pass a filepath that `rasterio` understands directly to `rio-tiler`. I.e.

```
COGReader('s3://bucket/path')
```

You should look up if you can do the same with GCS.

**Comment by nes123** [comment]
When I am trying to read directly from the cloud i get:

rasterio.errors.RasterioIOError: CPLRSASHA256Sign() not implemented: GDAL must be built against libcrypto++ or libcrypto (openssl)

**Comment by nes123** [comment]
saving the file locally and then opening it solved the problem. Thank you for your help.
