### ISSUE TITLE
ImportError: cannot import name 'main' from 'rio_tiler' 

### ISSUE THREAD

**Issue by mehar50** [cogeotiff/rio-tiler#465]
I am facing this issue, I could not import main as rt_main. Actuallying am tring to run this colab https://colab.research.google.com/github/daveluo/zanzibar-aerial-mapping/blob/master/geo_fastai_tutorial01_public_v1.ipynb#scrollTo=0MuNmPfAEFPD    ...In **Load slippy map tile image from COG with rio-tiler and corresponding label with geopandas** section am facing this error

**Comment by vincentsarago** [comment]
`main` is not in rio-tiler since rio-tiler 2.0, please update your code or pin rio-tiler to `1.*`

```
!pip install rio-tiler~=1.*
```

**Comment by mehar50** [comment]
> `main` is not in rio-tiler since rio-tiler 2.0, please update your code or pin rio-tiler to `1.*`
> 
> ```
> !pip install rio-tiler~=1.*
> ```

Thank you so much! Worked for me
