### ISSUE TITLE
Investigate weird `tolerance condition error` issue when working with GOES dataset.

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#468]
This was first reported in https://github.com/developmentseed/titiler/issues/413#issuecomment-985319883

Their is a really weird behaviour when calling the `.colorinterp` property of the rasterio object within the COGReader:

```python
from rio_tiler.io import COGReader
with COGReader("http://static2.skysight.io/demo2.tiff") as cog:
    print(cog.dataset.colorinterp)
---------------------------------------------------------------------------
CPLE_AppDefinedError                      Traceback (most recent call last)
<ipython-input-4-be6c69e3f1c3> in <module>
      1 with COGReader("http://static2.skysight.io/demo2.tiff") as cog:
----> 2     print(cog.dataset.colorinterp)
      3 

rasterio/rasterio/_base.pyx in rasterio._base.DatasetBase.colorinterp.__get__()

rasterio/rasterio/_err.pyx in rasterio._err.exc_wrap_int()

CPLE_AppDefinedError: tolerance condition error
```

Interestingly it's not related to the `.colorinterp` property but it all goes back to the call to `get_zooms` https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/io/cogeo.py#L130-L131 because when we set the zooms we then get the normal behaviour (`get_zooms` performs Coordinate transformation from dataset CRS to TMS CRS, so by setting the zooms  in the Object init we don't do any coordinate transformation). 

```python
with COGReader("http://static2.skysight.io/demo2.tiff", minzoom=0, maxzoom=10) as cog:
    print(cog.dataset.colorinterp)
(<ColorInterp.red: 3>, <ColorInterp.green: 4>, <ColorInterp.blue: 5>)
```

💥 It's get even weirder. If we just use rasterio to open a dataset then put it in a VRT, we can see that it exit the VRT just fine (prints `i'm outside the VRT block`) but we still get `CPLE_AppDefinedError: tolerance condition error` 

```python
with rasterio.open("http://static2.skysight.io/demo2.tiff") as src:
    print(src.colorinterp)
    with WarpedVRT(src, dst_crs="epsg:3857") as vrt:
        print(vrt.bounds)  # print bounds to confirm, VRT worked
        pass

    print("i'm outside the VRT code")
    print(src.colorinterp)


(<ColorInterp.red: 3>, <ColorInterp.green: 4>, <ColorInterp.blue: 5>)
BoundingBox(left=-5434894.885056, bottom=-5434894.885056, right=5434894.885056, top=5434894.885056)
i'm outside the VRT code

---------------------------------------------------------------------------
CPLE_AppDefinedError                      Traceback (most recent call last)
<ipython-input-5-fb35a7cd9fa3> in <module>
      5 
      6     print("i'm outside the VRT code")
----> 7     print(src.colorinterp)
      8 

rasterio/rasterio/_base.pyx in rasterio._base.DatasetBase.colorinterp.__get__()
rasterio/rasterio/_err.pyx in rasterio._err.exc_wrap_int()

CPLE_AppDefinedError: tolerance condition error
```

cc @sgillies, I'll continue to investigate, but to me it's seems kinda a race condition or a GDAL error that could be ignored but still surface

GDAL warp prints the same error but still succeed to create the VRT 
```
$ gdalwarp /vsicurl/http://static2.skysight.io/demo2.tiff demo.vrt -of VRT -t_srs epsg:3857
ERROR 1: tolerance condition error
ERROR 1: tolerance condition error
ERROR 1: tolerance condition error
ERROR 1: tolerance condition error
Creating output file that is 25409P x 17200L.
Processing /vsicurl/http://static2.skysight.io/demo2.tiff [1/1] : 0Using internal nodata values (e.g. 0) for image /vsicurl/http://static2.skysight.io/demo2.tiff.
Copying nodata values from source /vsicurl/http://static2.skysight.io/demo2.tiff to destination demo.vrt.
...10...20...30...40...50...60...70...80...90...100 - done.
```

cc @rouault (might be of interest)

**Comment by vincentsarago** [comment]
Found a fix. 

In rasterio we already catch some error that should be warning: https://github.com/rasterio/rasterio/blob/master/rasterio/_warp.pyx#L696-L704

I'm going to PR rasterio and add a catch for this `tolerance condition error` issue

**Comment by rouault** [comment]
> cc @rouault (might be of interest)

@vincentsarago I've filed https://github.com/OSGeo/gdal/issues/4934

**Comment by vincentsarago** [comment]
thanks @rouault 🙏

**Comment by vincentsarago** [comment]
I've opened a ticker over rasterio https://github.com/rasterio/rasterio/issues/2353

I think GDAL is doing the right thing even if it's not clear to me how the `tolerance condition error` are handled. To me it seems there are some issues on the rasterio side because it seems that the `tolerance condition error` are raised after calling code where they could be produced 

```python
# Fails at src.colorinterp second call with CPLE_AppDefinedError: tolerance condition error
import rasterio
from rasterio.warp import calculate_default_transform
with rasterio.open("http://static2.skysight.io/demo2.tiff") as src:
    print("color interp:", src.colorinterp)
    t, w, h = calculate_default_transform(src.crs, "epsg:4326", src.width, src.height, *src.bounds)
    print(f"raster size: {w}x{h}")
    print("color interp:", src.colorinterp)

>> color interp: (<ColorInterp.red: 3>, <ColorInterp.green: 4>, <ColorInterp.blue: 5>)
>> raster size: 28244x11988

---------------------------------------------------------------------------
CPLE_AppDefinedError                      Traceback (most recent call last)
<ipython-input-4-4a821cb8544a> in <module>
      6     t, w, h = calculate_default_transform(src.crs, "epsg:4326", src.width, src.height, *src.bounds)
      7     print(f"raster size: {w}x{h}")
----> 8     print("color interp:", src.colorinterp)

~/Dev/vincentsarago/rasterio/rasterio/_base.pyx in rasterio._base.DatasetBase.colorinterp.__get__()
   1249             out = []
   1250             for bidx in self.indexes:
-> 1251                 value = exc_wrap_int(
   1252                     GDALGetRasterColorInterpretation(self.band(bidx)))
   1253                 out.append(ColorInterp(value))

~/Dev/vincentsarago/rasterio/rasterio/_err.pyx in rasterio._err.exc_wrap_int()
    186         exc = exc_check()
    187         if exc:
--> 188             raise exc
    189     return err
    190 

CPLE_AppDefinedError: tolerance condition error
```

**Comment by malaretv** [comment]
Maybe worthy of it's own ticket but i'm bumping into similarly unhandled `tolerance condition error`s in the tile_exists check() here: https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/io/base.py#L109

**Comment by vincentsarago** [comment]
@malaretv I think it's the same issue. Is it happening with GOES data as well?

**Comment by malaretv** [comment]
@vincentsarago My case is various lunar datasets (in eqc and polar stereographic) trying to output tiles in a polar-rotated TMS (`+proj=ob_tran +o_proj=eqc +o_lon_p=180 +o_lat_p=0 ...`). So the `tolerance condition error`s i'm getting in `tile_exists()` are almost certainly warranted, just need to be handled.

**Comment by vincentsarago** [comment]
Good news, this will be fixed in next rasterio release 🥳, I'm going to close here because there is nothing to change in rio-tiler 🙏
