### ISSUE TITLE
maybe mistake in xy offset in error message

### ISSUE THREAD

**Issue by tsjsdbd** [cogeotiff/rio-tiler#471]
when File broken, the error message maybe have mistake:

Read or write failed. IReadBlock failed at ```X offset 7, Y offset 28```: /tmp/200504_08_83807.tif, band 1: IReadBlock failed at ```X offset 7, Y offset 7```: TIFFReadEncodedTile() failed.

you can see, when error occur, the error message is not consistent.  xy=[7,28]  , xy=[7,7]

**Comment by vincentsarago** [comment]
The error message comes from Rasterio/GDAL, nothing to do with rio-tiler. Sorry

**Comment by tsjsdbd** [comment]
@vincentsarago 
A digression. Can we organize COG-TIFF tiles according to the size projected by Mercator, so that tiles are not crossed each time they are fetched. In this way, only the smallest HTTP request needs to be sent.
![image](https://user-images.githubusercontent.com/7219402/146909784-ad860233-b4b9-461d-a2db-1c925c6cc5a7.png)
from here

**Comment by vincentsarago** [comment]
@tsjsdbd you need to create a `web-optimized` COG, meaning you need to have the data and the overview aligned with the WebMercator grid 
see https://gdal.org/drivers/raster/cog.html#reprojection-related-creation-options
> TILING_SCHEME=CUSTOM/GoogleMapsCompatible/other: Default value: CUSTOM. If set to a value different than CUSTOM, the definition of the specified tiling scheme will be used to reproject the dataset to its CRS, select the resolution corresponding to the closest zoom level and align on tile boundaries at this resolution. The tile size indicated in the tiling scheme definition (generally 256 pixels) will be used, unless the user has specified a value with the BLOCKSIZE creation option, in which case the user specified one will be taken into account (that is if setting a higher value than 256, the original tiling scheme is modified to take into account the size of the HiDPi tiles). In non-CUSTOM mode, TARGET_SRS, RES and EXTENT options are ignored. Starting with GDAL 3.2, the value of TILING_SCHEME can also be the filename of a JSON file according to the OGC Two Dimensional Tile Matrix Set standard, a URL to such file, the radical of a definition file in the GDAL data directory (e.g. FOO for a file named tms_FOO.json) or the inline JSON definition.

or https://cogeotiff.github.io/rio-cogeo/Advanced/#web-optimized-cog

**Comment by tsjsdbd** [comment]
Thank you very much, the performance has been greatly improved.
before：
![image](https://user-images.githubusercontent.com/7219402/147376817-8fd0980a-ea35-4656-bf0c-678063638050.png)
after：
![image](https://user-images.githubusercontent.com/7219402/147376823-bd999562-9b8e-4058-b523-f82ed5821ce1.png)
