### ISSUE TITLE
rio-tiler v3 on conda

### ISSUE THREAD

**Issue by ashnair1** [cogeotiff/rio-tiler#473]
Is there an ETA on when v3 of rio-tiler will be available on conda? Right now the latest version is 2.1.4

**Comment by vincentsarago** [comment]
@ashnair1 we do not manage the conda package.

you can raise the issue over https://github.com/conda-forge/rio-tiler-feedstock, but seems that automatic deployments are failing https://github.com/conda-forge/rio-tiler-feedstock/pull/19
