### ISSUE TITLE
pixel_selection is set to highest, but defaults.py will still stitch tiles with low pixel values(with mosaic), resulting in noticeable mosaic

### ISSUE THREAD

**Issue by jackcjp** [cogeotiff/rio-tiler#482]
Env:
 win10 version 19044.1466
titiler.application: 0.4.0
cogeo_mosaic:  4.0.0
rio-tiler: 3.0.3
pixel_selection: highest
python3.8

Two tif files in assets in same area: one is 10 meters, the other is 0.8 meters,
Here are the tif files:
[0.8 meter](https://drive.google.com/file/d/12VRdfU80mQioG_oHpnaiZGupy5u8VEmo/view)
[10 meter](https://drive.google.com/file/d/1-9YVEs_iTXdMdcIy5UJ3gsunnX5hc6vh/view)

Use titiler api to get img
:host/mosaicjson/tiles/WebMercatorQuad/z/x/y?format=webp&pixel_selection=highest&url=sqlite:///base.db:amosaic

Expect results:
get the img data only from the 0.8 meter (highest pixel calues), that is: only return data from the highest pixel tif instead of stitching several tifs together

only generated by [0.8m](https://drive.google.com/file/d/1Uc6O74HZbNzNuvzzj2dsyvm132fJJegV/view) 

Actual results:
get the img data by stitching both 0.8 meters and 10 meters, resulting in noticeable mosaic.

generated by [10m and 0.8m](https://drive.google.com/file/d/1nnQSv6SQj7cVKZBhmYQQZ8Y8gIUdcq1N/view) with pixel_selection highest

I thinks it was caused by the [numpy.bitwise_and](https://github.com/cogeotiff/rio-tiler/blob/b971d0e20bd74135ef67f87801c9107644af4fef/rio_tiler/mosaic/methods/defaults.py#L35-L37) method.

Here are the webp imgs:
only generated by [0.8m](https://drive.google.com/file/d/1Uc6O74HZbNzNuvzzj2dsyvm132fJJegV/view) 
only generated by [10m](https://drive.google.com/file/d/1QY9Uspfu1cf0WLOAqkI-sgYckGZz8YW1/view)
generated by [10m and 0.8m](https://drive.google.com/file/d/1nnQSv6SQj7cVKZBhmYQQZ8Y8gIUdcq1N/view) with pixel_selection highest

Is it an irregular tif error or any other error else?
Can anyone help me? Thank you!

@vincentsarago @kylebarron

**Comment by vincentsarago** [comment]
`highest` means **highest pixel value** not highest resolution.

To get `highest` resolution you'll have to first `sort` your input before using the `mosaic_reader`. Sadly the `mosaic_reader` nor the mosaic selection object do no have access to the source dataset.

**Comment by vincentsarago** [comment]
![](https://user-images.githubusercontent.com/10407788/154036618-8accb731-8786-4813-98b8-70affbe118e0.png)
