### ISSUE TITLE
COGReader constructor doesn't actually take a crs parameter

### ISSUE THREAD

**Issue by adair-kovac** [cogeotiff/rio-tiler#527]
Tested this in 3.1.6 and 3.1.0.

The COGReader constructor says it takes a "crs" parameter for the dataset crs:

> crs (rasterio.crs.CRS): Dataset CRS.

However, actually passing this parameter results in an immediate error.

```
from rio_tiler.io import COGReader
import rasterio

with COGReader("s3://hrrrzarr/sfc/20210101/20210101_00z_anl.zarr/surface/TMP/surface/TMP",
              crs=rasterio.CRS.from_dict(proj_params)) as image:
    print(image.dataset)
```

Error:

> TypeError: __init__() got an unexpected keyword argument 'crs'

Without the crs parameter, COGReader can read the zarr dataset in that example, but the dataset itself doesn't contain the CRS info so I can't do much with the resulting image. Please let me know if there's a workaround to set the dataset crs.

**Comment by vincentsarago** [comment]
@adair-kovac sorry about that. CRS is a property not an attribute.

list of inputs are defined here https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/io/cogeo.py#L80-L107

I'll fix the doc later.

About reading Zarr dataset, if GDAL doesn't recognize the geo-information, COGReader won't be able to work properly with the dataset.

**Comment by vincentsarago** [comment]
I've updated the docstring in https://github.com/cogeotiff/rio-tiler/commit/5f73ec1acd0eb4ce97704573d5687db6782aed19#diff-9c05aca328b2260df1dc8e2696999b4fba3d1966638e78c5d3265091bb4fdf01

**Comment by adair-kovac** [comment]
Ah, thank you!
