### ISSUE TITLE
moving from `flit` to `hatch`

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#538]
Every cool kids are moving to hatch (for good reasons) and I think we should do the same ;-) 

ref: https://github.com/pypa/hatch

**Comment by ofek** [comment]
Let me know if I can help!

**Comment by vincentsarago** [comment]
@ofek feel free to start a PR if you want 🙏

**Comment by vincentsarago** [comment]
Ah ah ah ah sorry @ofek I didn't realized you were the creator of Hatch 😅

**Comment by ofek** [comment]
Ha no worries 🙂

**Comment by vincentsarago** [comment]
done in https://github.com/cogeotiff/rio-tiler/pull/556/commits/ad1349366dd613958dbdaf291de1d224b5e22075
