### ISSUE TITLE
make use of file stac-extension `header_size` in MultiBaseReader 

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#550]
in https://github.com/stac-extensions/file there is a `header_size` info which in theory could be used to increase `GDAL_INGESTED_BYTES_AT_OPEN` https://developmentseed.org/titiler/advanced/performance_tuning/#gdal_ingested_bytes_at_open and reduce the number of GET request for accessing the asset.

## How to 

- refactor `MultiBaseReader._get_asset_url` 
https://github.com/cogeotiff/rio-tiler/blob/da7b8b315f53418d6e8b36138f6131020da5e484/rio_tiler/io/base.py#L270-L273

to return a dictionary in form of `{"url": str, "env": Optional[Dict]}`

- The `env` could then be used in https://github.com/cogeotiff/rio-tiler/blob/da7b8b315f53418d6e8b36138f6131020da5e484/rio_tiler/io/base.py#L304-L307

like 
```python
def _reader(asset: str, **kwargs: Any) -> Dict:
    asset_info = self._get_asset_url(asset)
    with rasterio.Env(**asset_info.env):
        with self.reader(asset_info.url, tms=self.tms, **self.reader_options) as cog:  # type: ignore
            return cog.info()
```

cc @geospatial-jeff

**Comment by geospatial-jeff** [comment]
Yes!!  This will be a nice performance increase especially on big images where the header size exceeds the default value of `GDAL_INGESTED_BYTES_AT_OPEN` requiring multiple GET requests to fetch the header.
