### ISSUE TITLE
Wrong pixel size (x and y) in transform

### ISSUE THREAD

**Issue by nkarasiak** [cogeotiff/rio-tiler#584]
Hi, 

First, thanks for this awesome python library!

I've just a bug where the transform (I mean the pixel size) is a different one on rio-tiler than on the original data when I ask a part on the image. 

When I open the tif with rasterio, here is the following transform (don't take into account the coords, just the pixel size, so **30m**, it's a a subset of a Landsat scene)  :
```
 | 30.00, 0.00, 350205.00|
| 0.00,-30.00, 4837995.00|
| 0.00, 0.00, 1.00|
```

But I got this with rio-tiler (**30.05** and **-29.97**) : 
```
| 30.05, 0.00, 353386.30|
| 0.00,**-29.97**, 4836581.80|
| 0.00, 0.00, 1.00|
```

For information, here are the versions of the libraries I used : 

- rio_tiler 4.1.9
- gdal : 3.6.1
- rasterio : 1.3.4
- python : 3.11 (same on 3.10)

The code to reproduce this bug is here : https://github.com/nkarasiak/bugs_demo/blob/main/rio_tiler/wrong_transform.py

Nicolas.

**Comment by vincentsarago** [comment]
This is because the bounds *is not aligned with the dataset pixels*. if you look at 👇, you'll see that the `window` we create from the bounds is not made of `round` numbers. This is why the `output` resolution is a bit different.

```python
from rio_tiler.io import Reader

import rasterio
from rasterio import windows


rst = "https://github.com/nkarasiak/bugs_demo/raw/main/rio_tiler/bouconne.tif"
bounds = 353386.3, 4830677.4, 359907.0, 4836581.8

with Reader(rst) as src:
    print("dataset transform")
    print(src.dataset.transform)
    print()
    img = src.part(bounds, bounds_crs=src.dataset.crs)
    print("output Part transform")
    print(img.transform)
    print()
    print("output image size")
    print(img.height, img.width)
    print()
    print("dataset window from bounds")
    window = windows.from_bounds(*bounds, transform=src.dataset.transform)
    print(window)
    print()
    print("Rasterio Read")
    arr = src.dataset.read(window=window)
    print(arr.shape)

dataset transform
| 30.00, 0.00, 350205.00|
| 0.00,-30.00, 4837995.00|
| 0.00, 0.00, 1.00|

output Part transform
| 30.05, 0.00, 353386.30|
| 0.00,-29.97, 4836581.80|
| 0.00, 0.00, 1.00|

output image size
197 217

dataset window from bounds
Window(col_off=106.04333333333307, row_off=47.1066666666884, width=217.35666666666657, height=196.8133333332953)

Rasterio Read
(1, 197, 217)
```

```python
x_width = (359907.0-353386.3) / 30.0  # 217.35666666666705
y_width = (4836581.8 - 4830677.4) / 30.0.  # 196.81333333331472
```

**Comment by nkarasiak** [comment]
Thank you for your answer.

Given the behavior of several tools (like buildvrt with a bbox), and after discussing with some colleagues, we think that we should be able to keep the default pixel size. Moreover in this case the pixels from the rio-tiler output do not perfectly overlap the original raster's pixels.

Do you think it is possible to have a behavior that keeps the pixel resolution by including or excluding the pixels at the border of the coordinates ? That would be great !

**Comment by vincentsarago** [comment]
> Moreover in this case the pixels from the rio-tiler output do not perfectly overlap the original raster's pixels.

As explained, it's not rio-tiler's fault but the bounds you pass do not aligned with the raster transform matrix. 

```python
with rasterio.open(rst) as src:
    window = windows.from_bounds(*bounds, transform=src.transform)
    arr = src.dataset.read(window=window)
```
☝️ in pure `rasterio` you'll get the same result 

> Do you think it is possible to have a behavior that keeps the pixel resolution by including or excluding the pixels at the border of the coordinates ? That would be great !

Yeah you just need to define bounds better 🤷 I don't think it will be rio-tiler place to change the input bounds you give.

```python
from rio_tiler.io import Reader

import rasterio
from rasterio import windows

rst = "https://github.com/nkarasiak/bugs_demo/raw/main/rio_tiler/bouconne.tif"
bounds = (353386.3, 4830677.4, 359907.0, 4836581.8)
print(bounds)
x_width = (bounds[2]-bounds[0]) / res  # 217.35666666666705
y_width = (bounds[3]-bounds[1]) / res  # 196.81333333331472

max_x = bounds[0] + round(x_width) * res
max_y = bounds[1] + round(y_width) * res

bounds = (bounds[0], bounds[1], max_x, max_y)
print(bounds)
with Reader(rst) as src:
    print("dataset transform")
    print(src.dataset.transform)
    print()
    img = src.part(bounds, bounds_crs=src.dataset.crs)
    print("output Part transform")
    print(img.transform)
    print()
    print("output image size")
    print(img.height, img.width)
    print()

(353386.3, 4830677.4, 359907.0, 4836581.8)
(353386.3, 4830677.4, 359896.3, 4836587.4)
dataset transform
| 30.00, 0.00, 350205.00|
| 0.00,-30.00, 4837995.00|
| 0.00, 0.00, 1.00|

output Part transform
| 30.00, 0.00, 353386.30|
| 0.00,-30.00, 4836587.40|
| 0.00, 0.00, 1.00|
```

If you really think this should be a rio-tiler feature I'll be happy to review any PR 

this will be the part you might want to change https://github.com/cogeotiff/rio-tiler/blob/9b344d1a1551b89b6a73d8cb93b947181f1db958/rio_tiler/reader.py#L245-L430

**Comment by nkarasiak** [comment]
Thanks for the feedback and for the indication of the part we need to change if we want this behavior 👍  If so we'll do a PR of course 👍
