### ISSUE TITLE
Bug in raster cutline when geometry goes over edge

### ISSUE THREAD

**Issue by yellowcap** [cogeotiff/rio-tiler#585]
The cutline behavior gives unexpected results when a geometry goes over the edge.

For a polygon like in the image below, the cutline algorithm will cut too much of the data. The reason seems to be that when computing the cutline coordinates in pixel space, the values are ["snapped" linearly to the edge](https://github.com/cogeotiff/rio-tiler/blob/main/rio_tiler/utils.py#L538) when they go over the image edge.

This snapping will essentially project the coordinates horizontally (or vertically) onto the edge. In the case of the image below, this implies that the triangle that is cut out is too big (the angle changes).

![tiranlge_example_qgis](https://user-images.githubusercontent.com/901647/227511472-e7cd42dd-7695-4455-a6e8-c1c43e1a4a90.png)

This problem can be fixed by simply skipping the snapping step. I tried this out and GDAL does not complain when the pixel coordinates go over the max size of the image. So I will propose a fix, but maybe there is a reason why the coordinates were limited in the first place that I am not aware of.

Here is hare plots of the cutline mask with and without the snapping mechanism.

Current behavior:

![Figure_1](https://user-images.githubusercontent.com/901647/227512431-d7835483-acf0-47ea-86cf-6dd8042bf29b.png)

Expected behavior (produced by simply skipping ines 538 and 539):

![Figure_2](https://user-images.githubusercontent.com/901647/227512445-57fc0dae-80f2-4015-a309-fba1591fa18b.png)

**Comment by vincentsarago** [comment]
closed in #586
