### ISSUE TITLE
The apply_color_formula function is failing to apply color_formula

### ISSUE THREAD

**Issue by kirangkumar** [cogeotiff/rio-tiler#601]
Hey, 
I have a local titiler that uses ```rio-tiler```, whenever I tried using the``` colormap_formula``` in the new version of rio-tiler which is 4.1.0. The rio-tiler is failing as it is unable to override the ```self.array.data``` inside ```models.py``` file.

The error I receive is : ```{"detail":"can't set attribute 'data'"}```

The color formula I am trying to apply ```color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55```

Works perfectly fine with an older version of rio-tiler (tested in 3.0.3)

Thanks

**Comment by vincentsarago** [comment]
Hi @kirangkumar, 
- what version of titiler are you using? 
- are you using a custom factory? 
- can you share the full URL you're trying to use
- if you can, remove https://github.com/developmentseed/titiler/blob/main/src/titiler/application/titiler/application/main.py#L114 then we will get a full error logs

**Comment by kirangkumar** [comment]
Hi @vincentsarago 

1. what version of titiler are you using?
- I am using the latest version titiler from main branch 
2. are you using a custom factory?
No I am not using custom factory
3. can you share the full URL you're trying to use
The URL is ```http://127.0.0.1:9070/stac/preview?format=png&url=https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-8-c2-l2/items/LC08_L2SP_229061_20220324_02_T1&assets=SR_B4&assets=SR_B3&assets=SR_B2&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55```
4. Error message:
Hope this is sufficient: 
```
  File "/Users/kiran/pixxel/titiler/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/kiran/pixxel/titiler/src/titiler/core/titiler/core/factory.py", line 914, in preview
    image.apply_color_formula(color_formula)
  File "/Users/kiran/pixxel/titiler/venv/lib/python3.10/site-packages/rio_tiler/models.py", line 551, in apply_color_formula
    self.array.data = scale_dtype(ops(to_math_type(out)), numpy.uint8)
AttributeError: can't set attribute 'data'
```

**Comment by vincentsarago** [comment]
the latest titiler shouldn't be used with rio-tiler <4.1.6

https://github.com/developmentseed/titiler/blob/main/src/titiler/core/pyproject.toml#L38

**Comment by vincentsarago** [comment]
any update @kirangkumar ?

**Comment by kirangkumar** [comment]
@vincentsarago Sorry was busy with other stuffs, the rio-tiler version I m using is 4.1.10 which is greater than 4.1.6. So I feel it should work

**Comment by kirangkumar** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/111843957/234354217-cba5a130-3f74-496e-be8a-44dc15e85b19.png">
Here's the details about rio-tiler version I am using.

**Comment by kirangkumar** [comment]
And I am using one band in one file, so I guess, asset_as_band=True is not required. But I tried that option too before creating the issue, since there was no luck, I thought of asking help here

**Comment by kirangkumar** [comment]
@vincentsarago No worries, thanks for the quick help. I will upgrade my code from dev to main. Can you please let me know what is the version in main?

**Comment by vincentsarago** [comment]
`main` should be 4.10

**Comment by vincentsarago** [comment]
this should be fixed with latest commit https://github.com/cogeotiff/rio-tiler/commit/ee1d7c4c14a23c3f5a16b91a63197e1f402e218c

please could you close the issue once you confirm it's resolved on your side 🙏

**Comment by kirangkumar** [comment]
Amazing! I will close the issue, thanks for all the help.

But I feel even ```main``` also has the same code as ```dev```.

https://github.com/cogeotiff/rio-tiler/blob/b7ce316bdb69aac48b3792bf9d26ac634c9426e5/rio_tiler/models.py#L493

Can you please help me with the right branch for 4.1.0 or you would recommend me to use from PyPi?

**Comment by kirangkumar** [comment]
@vincentsarago thanks for all the support. I can confirm it is working for me. Thanks again, closing the issue
