### ISSUE TITLE
XarrayReader.tile returning `At least one of the clipped raster x,y coordinates has only one point.`

### ISSUE THREAD

**Issue by abarciauskas-bgse** [cogeotiff/rio-tiler#607]
Working with titiler-xarray, we are seeing many of these errors:

```
{
  "detail": "At least one of the clipped raster x,y coordinates has only one point. Data variable: tas"
}
```

Example URL:
https://dev-titiler-xarray.delta-backend.com/tiles/10/618/664.png?variable=tas&rescale=200,300&url=s3://cmip6-pds/CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r2i1p1f1/Amon/tas/gn/v20180827/

Many more of these errors were experienced in performance testing.

Reproducing locally, I found the traceback:

```
File "/Users/aimeebarciauskas/github/developmentseed/titiler-xarray/titiler/xarray/factory.py", line 248, in tiles_endpoint
    image = dst.tile(
  File "/Users/aimeebarciauskas/miniconda3/lib/python3.9/site-packages/rio_tiler/io/xarray.py", line 222, in tile
    ds = self.input.rio.clip_box(*tile_bounds, crs=self.tms.rasterio_crs)
  File "/Users/aimeebarciauskas/miniconda3/lib/python3.9/site-packages/rioxarray/raster_array.py", line 817, in clip_box
    print(cl_array)
rioxarray.exceptions.OneDimensionalRaster: At least one of the clipped raster x,y coordinates has only one point. Data variable: tas
```

The root of the issue is that rio.clip_box only returns 1 data point for lat or lon. We can address this by adding the option to `auto_expand` the bounding box query.

My question about this approach is just would their be concerns about misrepresenting the data? I believe these could be alleviated with documentation and clients should only configure `auto_expand=True` when it is suitable for the use case. For instance, if visualization is intended to be a "good enough" representation. Another option for clients is just to set a maxzoom level to a number where this issue doesn't occur.

**Comment by vincentsarago** [comment]
@abarciauskas-bgse thanks for starting the issue. The proposed fix seems good to me but I'm not sure to understand what would be the results of such a thing, and why this could not be set to `true` by default. 

Are you sure that the output will be visually good?

**Comment by abarciauskas-bgse** [comment]
in some local testing, the visual experience is "fine" in that when you zoom in you just have very large blocks of the same color, which is kind of what I expected. I wouldn't expect most users to even want to zoom in this high for datasets which have this issue.
<img width="1774" alt="Screen Shot 2023-05-18 at 7 52 44 AM" src="https://github.com/cogeotiff/rio-tiler/assets/15016780/eb1feeb3-d7d9-434d-838d-c4a34baafd9b">

I tested with both `auto_expend=True` and `=False` so that I could assert the errors appear only in the latter case, when `auto_expand=False`. The thing is, with at least the mapping client I am using (mapbox), I think the tiles are only replaced when new ones are successfully fetched, so the user experience (at least in my limited testing) is no different if the setting is `True` or `False`. So in this case it just helps alleviate the error rate when requesting specific tiles.
