### ISSUE TITLE
Information about STACReader fetch_options 

### ISSUE THREAD

**Issue by nmochar2** [cogeotiff/rio-tiler#619]
Hi, 

Is there more information that can be provided about what can be defined with the fetch_options argument. I'm trying to query from a stac from behind a proxy server and am having issues identifying how I can pass certificate information to the STACreader. I'm assuming it would be defined in the fetch_options  I see that it's a stac.Item object and am unsure how to define it there. 

Thank you

**Comment by vincentsarago** [comment]
@nmochar2 the `fetch_options` is a dictionary of options that will be forwarded to either the `httpx.get` or `boto3.s3` methods 
https://github.com/cogeotiff/rio-tiler/blob/90bb3c8e36ee400b6916da02937e26560b66f45f/rio_tiler/io/stac.py#L98-L129

see https://www.python-httpx.org for the options available for httpx

**Comment by nmochar2** [comment]
Thank you! I was able to pass the cert using the verify option 

`
STACReader(input=uri, fetch_options={"verify": "ssl.crt"})
`
