### ISSUE TITLE
`NotGeoreferencedWarning` in `feature` 

### ISSUE THREAD

**Issue by JackDunnNZ** [cogeotiff/rio-tiler#627]
When calling `.feature` I am sometimes seeing a `rasterio.errors.NotGeoreferencedWarning` arising from this call to `rasterize`:

https://github.com/cogeotiff/rio-tiler/blob/584ecdbc204f4c2870250e777e69db89a7f3157f/rio_tiler/io/rasterio.py#L566-L574

It seems like the warning could be safely filtered, as `shape` is not required to specify a CRS?

**Comment by vincentsarago** [comment]
I wonder if this is more a rasterio issue 🤷 

Could you provide a code that reproduce the warning (because I can't reproduce)

**Comment by JackDunnNZ** [comment]
Great, thanks for the quick fix!
