### ISSUE TITLE
More Docs 

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#63]
This project needs better documentation

**Comment by vincentsarago** [comment]
We should add a note about nodata/alpha/mask handling ref #89

**Comment by vincentsarago** [comment]
Ref: love the docs from terracotta https://terracotta-python.readthedocs.io/en/latest/

**Comment by vincentsarago** [comment]
add implementation docs and examples

**Comment by vincentsarago** [comment]
Alright it's time, let's try mkdocs cc @kylebarron

**Comment by kylebarron** [comment]
> Ref: love the docs from terracotta [terracotta-python.readthedocs.io/en/latest](https://terracotta-python.readthedocs.io/en/latest/)

For the record, the docs from terracotta are using Sphinx, which I believe requires you to write in RST. If you're used to Markdown, trying to switch is really annoying.

**Comment by vincentsarago** [comment]
yep I'm totally down for mkdocs... just need time :D

**Comment by vincentsarago** [comment]
mostly done
