### ISSUE TITLE
InvalidGeographicBounds exception raised for datasets covering whole WGS84 extent

### ISSUE THREAD

**Issue by noahgolmant** [cogeotiff/rio-tiler#754]
Right now, if a dataset has extent equal to (-180, -90, 180, 90), then `XarrayReader` will [throw](https://github.com/cogeotiff/rio-tiler/blob/abec15162c1d8cf9dd67cb5945d8532e2b6f562c/rio_tiler/io/xarray.py#L79) an `InvalidGeographicBounds` exception. This is because `self.rio.bounds` actually applies a single pixel buffer to the internal dataset bounds based on the resolution of the dataset (see [here](https://github.com/corteva/rioxarray/blob/f3ad955dd59dfdd1a696ac9d4a4b5be1418c5994/rioxarray/rioxarray.py#L1079)).

Is this the desired behavior? If not, the fix should be relatively simple since we can apply a similar buffer to the bounds in that check.

**Comment by vincentsarago** [comment]
@noahgolmant feel free to start a PR 🙏
