### ISSUE TITLE
Reader get tile with cutline and vrt_options getting pixels shifted/missing from original mask applied

### ISSUE THREAD

**Issue by Martenz** [cogeotiff/rio-tiler#758]
### Context

I'm working on a COG tile API service (FastAPI) that distributes tiles from cloud storage buckets. All COGs use EPSG:3857 and cover a large area, specifically all of Italy. I'm using the Reader class from rio-tiler to read the COG and get the x, y, z tiles.

We store geometries in PostGIS in EPSG:3857, which are queried as geojson (::jsonb) with sqlalchemy from the db

```
...
qry = text(f"""SELECT 
            ST_AsGeoJson(ST_Union(ST_Transform("{mask_dbgeom}",3857)))::jsonb as mask
                FROM {mask_dbschema}.{mask_dbtable}
                    {wherec}""")
...
```

and then used as masks to clip the raster.
My main endpoint, which retrieves the x, y, z tile, returns the tile as follows:

```python
with gdal_env, reader_class(url) as cog:
    cutline = create_cutline(cog.dataset, geo_mask, geometry_crs="epsg:3857")
    vrt_options = {
                        "cutline": cutline,
                        "crop_to_cutline": True
                    }
    img = cog.tile(x, y, z, vrt_options=vrt_options)
``` 

The cutline is computed using the **rio-tiler** utility **create_cutline**, passing the ST_AsGeoJSON representation of the mask geometries.

### The problem and my solution

Once the raster is rendered on the map, the cropped pixels seem shifted to the left, either outside the applied mask/cutline or missing inside the mask. I tried different configurations of VRT optional parameters, but none worked.

<img width="496" alt="Screenshot 2024-10-25 alle 00 30 31" src="https://github.com/user-attachments/assets/07dcd939-b34e-4d93-9eeb-295bae7b15a8">

After some investigation, I found that the **create_cutline** method calls the **_convert_to_raster_space** function, which uses the **rasterio** method **rowcol**.

The **rowcol** method has an optional parameter **op** (operator I guess), which defaults to flooring the float result of raster space indexing, and this cannot be changed when calling **_convert_to_raster_space**. I temporarily modified **_convert_to_raster_space** to accept the op parameter and used **Round**, which finally resolved my pixel shift issue.

<img width="557" alt="Screenshot 2024-10-25 alle 00 38 56" src="https://github.com/user-attachments/assets/a4d470e6-cf94-4df6-99ab-f406f207f54f">

### Questions

- Do you think this issue is related to the transform of my original COG files?
- is someone facing the same problem?
- Is this a valid solution? If so, would it be feasible to expose the op parameter in the create_cutline method to address similar issues?

Thanks.

**Comment by vincentsarago** [comment]
Hi @Martenz 
thanks for a great issue report 🙏 

> Is this a valid solution? If so, would it be feasible to expose the op parameter in the create_cutline method to address similar issues?

I think this is an acceptable change. would you be able to create a PR for this?

**Comment by Martenz** [comment]
> Hi @Martenz thanks for a great issue report 🙏
> 
> > Is this a valid solution? If so, would it be feasible to expose the op parameter in the create_cutline method to address similar issues?
> 
> I think this is an acceptable change. would you be able to create a PR for this?

I guess so, might have some problems with UT but I can try. Would be nice to contribute! Thanks for your feedback
