### ISSUE TITLE
Error adding mask as alpha channel

### ISSUE THREAD

**Issue by a2hill** [cogeotiff/rio-tiler#89]
### Problem
Calling `array_to_image` using the array and mask returned from `tile` using a 4 band tiff returns an error:  `WEBP driver doesn't support 5 bands. Must be 3 (RGB) or 4 (RGBA) bands.` 

### Relevant code
```
# image at URL is 4 band geotiff
tile, mask = main.tile(url, int(tile_x), int(tile_y), int(tile_z), tilesize=256, nodata=None)
options = img_profiles["webp"]
buffer = utils.array_to_image(tile, mask=mask, img_format="webp", color_map=None, **options)
```
### Possible Cause
It looks like [utils:392](https://github.com/cogeotiff/rio-tiler/blob/2544ff414974b2a7a1b7dbdd84d941e21eca6078/rio_tiler/utils.py#L392) is just adding a band to the array without checking to see whether an alpha band already exists

**Comment by vincentsarago** [comment]
👋 @a2hill sorry for this `bug` 
I don't see a fix directly to the `array_to_image` function but to me it seems you could pass `indexes=(1,2,3)` to the data function and then the mask return should be the alpha band. 

Handling nodata/mask/alpha band is a tricky thing (I've worked on the matter all the week), maybe `utils.tile_read` could remove the alpha band from the `data` array directly ?

**Comment by vincentsarago** [comment]
@a2hill where you able to have your code fixed ? 
I'm going to close this issue, but feel free to re-open if you have more questions.

Note: I've added a note in #63 to add more documentation about nodata/alpha handling.

**Comment by a2hill** [comment]
@vincentsarago Yes we implemented additional check's for 4 band images and handle them differently. I think the older version of `array_to_img` used a `has_alpha` check, was that specific to PIL support?

**Comment by vincentsarago** [comment]
@a2hill I'll need to check but maybe this https://github.com/cogeotiff/rio-tiler/blob/9aa45d68b08b116740792441405bd3003f4a1bd8/rio_tiler/utils.py#L537

was taking care of it because it forced the data to be 3bands.

I'm kinda happy/not happy about the situation but I do believe that using the new gdal based function let's the user do more thing (e.g enable to save GeoTIFF). But maybe we still could add a test for data that have more than 3 bands and not saved as 'GTiff'.

**Comment by a2hill** [comment]
I agree, I like the new gdal based image function as well. I think it is going to be a lot more helpful with single band images as well. Previously I was having to do linear scaling to convert my dem's from `float` to `uint8` but it looks like I no longer will need to do that with the gdal based function?

**Comment by vincentsarago** [comment]
@a2hill well I think GDAL will throw an error if your data is not in `uint8`, before we had a test to `cast` the data to uint8 but again we removed it to let the user decide in their own implementation (mostly to support other format).

**Comment by a2hill** [comment]
Ah okay nevermind then! Related but kind of off topic, are you planning support to allow color_map files which use the [GDAL color configuration syntax](https://www.gdal.org/gdaldem.html#gdaldem_color_relief)?

**Comment by vincentsarago** [comment]
@a2hill when I started working on the new function I tried to use the internal gdal method (https://github.com/mapbox/rasterio/blob/master/docs/topics/color.rst#writing-colormaps) but I couldn't get it to work (If I remember well my problem was that I had to first write the file to the disk before being able to see the colormap applied data.

I could have a second look later, but if you ever want to start a PR to update `array_to_image` or add a new function, please feel free. 

Also I'm also happy to see how people use rio-tiler 😄

**Comment by a2hill** [comment]
@vincentsarago Thanks for pointing that out. I may have a look at that as I am currently looking into integrating support for [colorbrewer2 palettes](http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) via [palettable](https://github.com/jiffyclub/palettable) for DEM's. If I find a better way to apply the color maps I'll be sure to submit a PR.
